### ISSUE TITLE
Update to Checkstyle 8.7

### ISSUE THREAD

**Issue by lkoe** [checkstyle/eclipse-cs#1]
Update the plugin to Checkstyle 8.7

**Comment by lkoe** [comment]
#2

**Comment by romani** [comment]
Please review labels at checkstyle project, if you agree with them, we can start to use them in this project too. All of them targeted to let contributor known status of issue, the most critical is label "approved" to make it clear that fix is wellcome we all agree on fix. Issues without it are in discussion or incomplete or ... .

**Comment by romani** [comment]
Additional point is that 8.7 release is special release to just introduce painful but easy api damage.
It would be awesome to make release to 8.6 , as only it contains metadata changes and next do one more release that will demand from you only version bump

**Comment by lkoe** [comment]
Regarding labels: yes, good idea to align this approach. 

Regarding separate 8.6/8.7 releases: I'd rather not since it's quite some work for me and the intermediary release holds no value für plugin users. I agree, however, that having releases in "lock-step" would be preferable in the future.

**Comment by romani** [comment]
@lkoe , I created milestone for you https://github.com/checkstyle/eclipse-cs/milestones
it is better to mark issue with milestone to share where/when it will be released, to avoid extra conversations from comunity.

**Comment by rwalkerands** [comment]
Is this release now meant to be available on the update site? (It still points to 8.5.1.)

**Comment by romani** [comment]
It is implemented but not released yet, https://github.com/checkstyle/eclipse-cs/releases 

@lkoe , it would be awesome if you just make a release. Do not wait for extra fixes, just checkstyle update is more than enough. Sevntu release is blocked by eclipse-cs .

**Comment by lkoe** [comment]
@romani I'll do it asap, but likely not before Jan 13
