### ISSUE TITLE
Document what remains at sourceforge

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#10]
I'm not completely sure what is intended to remain at Sourceforge. As far as I know, the sources and the issue tracking are meant to be at Github, but the website is still hosted at Sourceforge. Do you plan to leave some parts like the website at Sourceforge, or should everything be migrated?

**Comment by lkoe** [comment]
Ideally everything should be migrated from Sourceforge. Sources, Issues and Wiki are no brainers.

 ## Binary downloads
Update site binaries are already located on Bitbucket for better reliability, packaged update site could go there as well

## Project website
If possible move it to Github pages.
The site is build on Angular 1.4 as a single page app and is dual-used to provide Eclipse help content.
However, it uses a tiny amount of PHP (https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.doc/src/main/resources/index.php) to make the site crawlable for search engines - that won't fly on GH Pages, so an alternative is required for that. 

## Discussion forums
There isn't much activity, we could likely vacate the premises.

**Comment by romani** [comment]
core project use google groups for questions, it is used somehow (not very frequently), but in most cases users open github issues, or go to stackoverflow.

**Comment by lkoe** [comment]
Project website has moved to Github pages: https://checkstyle.github.io/eclipse-cs/
Redirect from the Sourceforge page has been added, works for the old update site URL as well.

There are still references to the old URL in plugin files and external sources (Bitbucket, Marketplace) which will be ironed out in the next days.

**Comment by Bananeweizen** [comment]
I just submitted 2 related pull requests, because I edited those files before I read your comment here. :)

**Comment by mnlipp** [comment]
Currently, no update-site is available. Marketplace (still) tries to access `http://eclipse-cs.sourceforge.net/update/`, which doesn't work. The [github page](https://checkstyle.github.io/eclipse-cs/#!/) has at its bottom `net.sf.eclipsecs-updatesite/target` which is complete nonsense. How can I find the update-site on bitbucket?

**Comment by lkoe** [comment]
Right now sourceforge itself (or at least project websites) are not available, for instance [http://checkstyle.sourceforge.net/](http://checkstyle.sourceforge.net/) is also not working...

It is intended that all old URLs should still work, redirecting to the new URLs. Of course when the old site is down entirely that's a problem...

The new update site URL is: `https://checkstyle.github.io/eclipse-cs/update/`
