### ISSUE TITLE
"Ignore optional compile problems" broken in Eclipse 2018-09 (4.9.0)

### ISSUE THREAD

**Issue by bentatham** [checkstyle/eclipse-cs#104]
I'm not sure what happened, but when I upgraded (fresh install) of Eclipse 2018-09 (4.9.0) Build 20180917-1800, using Eclipse Checkstyle Plugin 8.12.0.201808161509, the checkstyle warning/problems still appear in the Problems view for source directories marked with "Ignore optional compile problems". (In my case, that is generated-sources directories).

This used to work (ie it used to hide these warnings) when using the June release of Eclipse.  

Or I have missed something else I need to set in my eclipse configuration.  I don't see anything else to set in the Checkstyle preferences in Eclipse.

**Comment by bentatham** [comment]
Oops.  Need to check "derived (generated) files" in the per-project Checkstyle settings under "Exclude from checking...".  Equivalent to this in the `.checkstyle` file

`<filter name="DerivedFiles" enabled="true"/>`

**Comment by Bananeweizen** [comment]
To avoid such issues, you may want to just add the update site url of the new eclipse version in your existing installation, and upgrade in-place. I do that with all installations since years and never had any trouble.
