### ISSUE TITLE
Missing target platform configuration

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#11]
The repository does not contain a .target file to configure the target platform for the plugin development environment. That way, the plugin sources are always compiled against the bundles of the running Eclipse IDE, thereby easily introducing incompatible changes for older versions of Eclipse.

Did I miss something here or shall I create and contribute such a target definition?

**Comment by lkoe** [comment]
Indeed, I've so far only used a target definition in the tycho build. In eclipse I always used the latest release and have users report accidental incompatibilities to older versions.

In any case, please go ahead with your proposal.
