### ISSUE TITLE
Write Tag cannot be used on Variables

### ISSUE THREAD

**Issue by 2129zxl** [checkstyle/eclipse-cs#116]
I wanna to check my variables with specific Javadoc tag like below:

/**
* @myowntag: somevalue
*/
public String myVariableDef;

I found that "writetag" module can do the similar thing but it cannot accept "VARIABLE_DEF" type, while other types like CLASS_DEF, ANNOTATION_DEF are all permitted.
So could you experts help to solve this?

**Comment by rnveach** [comment]
@2129zxl This is an issue with the main [checkstyle](https://github.com/checkstyle/checkstyle) utility. Eclipse-cs just maintains a eclipse plugin of checkstyle.

`WriteTag` is a bad design and deprecated by the checkstyle maintainers so you may not find any support to extend it. See https://github.com/checkstyle/checkstyle/issues/3669#issuecomment-268396283 .
