### ISSUE TITLE
Allow to specify a separate supression file

### ISSUE THREAD

**Issue by Serranya** [checkstyle/eclipse-cs#117]
I have the following use case.

I am specifying the checkstyle configuration via maven inline rules (https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/inline-checker-config.html).
I also specify a supression file via maven.

I am using the https://github.com/m2e-code-quality/m2e-code-quality plugin to read these informations from the pom and configure eclipse-cs accordingly.

This is working for the rules. But not for the supression file. Is it somehow possible to specify a separat supression file in eclipse-cs? So that the m2e-code-quality plugin can read it from the pom and pass it.

**Comment by romani** [comment]
>I also specify a supression file via maven.

Example please

**Comment by Serranya** [comment]
I specify the supression file like this:
https://github.com/Serranya/de.serra.rocker-for-takes-maven-plugin/blob/master/pom.xml#L26

The main checkstyle config can be found in the parent project here:
https://github.com/Serranya/de.serra.parent/blob/0797f34212dc525781984a661bf08096825ed0e5/pom.xml#L411-L522

If there is another way to handle this I don't know of it.

**Comment by Serranya** [comment]
Ahh, I found a solution. Thanks for pointing me to the SuppressionFile filter.
