### ISSUE TITLE
Error (tools.jar not found) when Eclipse is not running with a JDK VM

### ISSUE THREAD

**Issue by extraneu** [checkstyle/eclipse-cs#131]
Steps to reproduce:
- Run Eclipse in a plain JRE (not JDK)
- Install the eclipse-cs plugin 
- Run a maven build for any project
Result:
- the build fails and an error is logged by eclipse-cs "cannot find <path_to_jre>\tools.jar"
- neither changing the default Installed Runtime, removing any plain JRE from the Instelled Runtimes, or changing the Eclipse VM doesn't have an effect
- re-instaliing the plugin (i.e. uninstalling in Installation Details windows and installing from the market again) fixes the problem.

It seems the plugin requires a JDK to run, and stores the path of the default Installed Runtime somewhere in its configuration?

**Comment by romani** [comment]
checkstyle library removed this dependency at https://github.com/checkstyle/checkstyle/issues/5431 ,  released as 8.9

**Comment by lkoe** [comment]
The plugin doesn't do anything specifically with the tools.jar. Please reopen if this still occurs using the most current plugin version.
