### ISSUE TITLE
Support Eclipse 2018-12 (4.10)

### ISSUE THREAD

**Issue by rimesc** [checkstyle/eclipse-cs#133]
The Checkstyle plugin doesn't appear in the marketplace client from Eclipse 2018-12, presumably because it isn't listed as a supported platform.

Are there compatibility issues and, if not, can the marketplace entry be updated?

**Comment by lkoe** [comment]
I've updated the marketplace listing, though I didn't test it with the latest Eclipse version due to lack of time.
If you encounter any issues, please report.
