### ISSUE TITLE
question: guess module name from the problem description

### ISSUE THREAD

**Issue by basinilya** [checkstyle/eclipse-cs#136]
When seeing a message like

    '+' should be on the previous line.

How do I guess that the related module is called "Whitespace/Operator Wrap" without browsing the source code?

**Comment by lkoe** [comment]
In the Checkstyle preferences (Window->Preferences->Checkstyle) there is an option to add the rule name to the violation message. That should do what you need.

**Comment by basinilya** [comment]
We're talking about Eclipse-cs, right? I don't see anything like that.

**Comment by lkoe** [comment]
yes, the option is called "include rule names in violation messages"
https://checkstyle.org/eclipse-cs/#!/preferences

**Comment by basinilya** [comment]
Many thanks. Closing.
