### ISSUE TITLE
Issue with Marker Hover for Custom Language

### ISSUE THREAD

**Issue by amitbhoraniya** [checkstyle/eclipse-cs#146]
Hi Team,

I have created custom checkstyle rules plugin for eclipse which adds new rules for JAVA language as well as Gherkin Language.

For JAVA Rules it displays error message, when I hover text or clicking on marker. But for my custom language, text hovering/clicking on marker icon not showing any error/warning message as a tooltip.

![msg1](https://user-images.githubusercontent.com/4617600/55467401-d7245180-561e-11e9-8675-6e70bf046193.png)
![msg2](https://user-images.githubusercontent.com/4617600/55467410-da1f4200-561e-11e9-9330-89c5ce12f953.png)

Here I have attached a screenshot, in which status bar and clicking on overview showing me error but it is not showing tooltip warning or error message. Can anyone help me here what I might have missed ?

**Comment by romani** [comment]
@amitbhoraniya , if you can share code of your custom Check it would be awesome, I would love to use it too.

**Comment by amitbhoraniya** [comment]
@romani Thanks. I validated it, rows and column number is expected. I debug it more and looks like editor specific issue. So closing it here. Really appreciate your help 👍
