### ISSUE TITLE
Add me to snyk organization

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#152]
I've just tried to inspect the snyk build results which are available for each pull request, e.g. https://app.snyk.io/org/checkstyle/test/github/4ba4dd1e-cdc1-4098-8752-b77e2db3a4ae/master..cee856cbf0b5a1e7f815a706c97dd7220603eda1?fromStatus=true

![image](https://user-images.githubusercontent.com/406876/57122558-4906cc80-6d7e-11e9-849c-6a69744a2bcb.png)

However, that gives an error for me. Can someone with the necessary power add my account to the organization on Snyk which is associated with checkstyle-cs project?

**Comment by rnveach** [comment]
Currently only me and @romani are the only admins. It is for whole checkstyle org, and not just eclipse-cs.
It requires us to invite someone by email.
@romani Please confirm and invite.
Should we add the synk badges to the readme so it shows on the main page?

**Comment by romani** [comment]
invitation was sent to "Mic....Ke....@g.d", if you use some other email for githiub, please send it to me.

**Comment by Bananeweizen** [comment]
Thanks, I'm in. However, the tool itself seems to work not that good on the EclipseCS POMs, as it lists zero dependencies for all that I checked (and therefore also does not raise any warnings).

**Comment by romani** [comment]
Disable if it doesn't work well

**Comment by Bananeweizen** [comment]
Maybe they fix their analysis at some future point of time. Right now it shows 0/0/0 warnings for the Eclipse related POMs, so it will also not block the pull requests. Therefore it is okay to leave it as it is.
