### ISSUE TITLE
Disable fast-forward requirement for PRs

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#159]
I'm not sure at what point of time this changed, but all of my recent PRs could not be merged. In all cases github complained about not being able to merge, unless I rebased each and every PR on the (then current) master locally and force-pushed again. So it looks like someone enforced fast-forward merges somehow on the repository. If anyone knows where that might be (I don't) please disable that setting. We have "rebase" as default merge strategy, which would have the same effect, if it were possible to click the button.

Or is it just me, and everyone else can merge PRs which are not based on current master?

**Comment by romani** [comment]
Yes, I limited merge abilities to be only rebase and merge. It requires manual rebase only when conflict happens, kind of reasonable demand.

Do you experience some other problems ?
