### ISSUE TITLE
Can we enforce https for web site ?

### ISSUE THREAD

**Issue by romani** [checkstyle/eclipse-cs#160]
I see in config:
![image](https://user-images.githubusercontent.com/812984/57194217-03bada00-6ef9-11e9-961e-35ce508376a9.png)

Is there any problems to activate "Enforce HTTPS" ?
or it was just forgotten .... 
We try to migrate off "http" web sites (latest security issues against project)

**Comment by lkoe** [comment]
I didn't know the option so far. Was it introduced at a later point?
In any case it's active now.
