### ISSUE TITLE
Show checkstyle violations in eclipse problems tab

### ISSUE THREAD

**Issue by BujakiAttila** [checkstyle/eclipse-cs#171]
It would be nice to see the Checkstyle violations in the "Problems" tab of eclipse as well and not only in the "Checkstyle violations" tab.

Is it possible to configure the plugin (or eclipse) to achieve this?

**Comment by Calixte** [comment]
Checkstyle violations should show up in your Problems tab by default.
![Screenshot from 2019-11-04 09-50-21](https://user-images.githubusercontent.com/4010811/68144521-bdb2f300-fee8-11e9-8aa6-16514d6e8dcb.png)

Using the down arrow on the top right of the view ("View Menu"), you can open the "Filters" configuration panel. Make sure "Checkstyle Problem" is selected in the "Types" section.

**Comment by BujakiAttila** [comment]
Thanks for the support.

Yes. Indeed. The "Checkstyle problems" were not selected:

![image](https://user-images.githubusercontent.com/2914096/68145853-fe395d80-ff36-11e9-98a5-7a8aaa616175.png)

I just had to change this setting. Great!
