### ISSUE TITLE
Release notes are not shown

### ISSUE THREAD

**Issue by romani** [checkstyle/eclipse-cs#176]
https://checkstyle.org/eclipse-cs/#!/releasenotes

in FF 70.
![image](https://user-images.githubusercontent.com/812984/68214961-3d959780-ff93-11e9-845a-f463aefeb047.png)

**Comment by rnveach** [comment]
Quickly glanced.
This JS file looks like it controls the release notes. https://checkstyle.org/eclipse-cs/js/main.js (Specifically see ReleaseNotesCtrl).
The JSON file does exist. https://checkstyle.org/eclipse-cs/releases.json
I see the executed page accessing the JSON file.

So something is happening after the file is retrieved.

I did happen to open the JSON in a JSON parser and got this error:
> SyntaxError: JSON.parse: expected double-quoted property name at line 25 column 3 of the JSON data

So this could be the issue.

**Comment by lkoe** [comment]
Error in browser console:
```
Error: JSON.parse: expected double-quoted property name at line 25 column 3 of the JSON data
cc@https://checkstyle.org/eclipse-cs/3rd-party/angular-1.2.26/angular.min.js:14:360
Ud/this.defaults.transformResponse<@https://checkstyle.org/eclipse-cs/3rd-party/angular-1.2.26/angular.min.js:69:261
...
```

Seems the comma at this position is the culprit:
https://github.com/checkstyle/eclipse-cs/blob/fb552f7dadd114047f18b6c124436860e9d18efe/net.sf.eclipsecs.doc/src/main/resources/releases.json#L24

**Comment by romani** [comment]
Thanks a lot for investigation.
I will fix it in next release, I hope it will be tomorrow

**Comment by Dichotomia** [comment]
See https://github.com/checkstyle/eclipse-cs/pull/178

**Comment by romani** [comment]
fix is merged
