### ISSUE TITLE
missing project settings for formatter

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#18]
While editing some of the Java code, I noticed it does not follow the Eclipse default formatting rules (mostly notable by 2 spaces indentation). Since there are no .prefs checked in with the Eclipse project, I assume you configured that in your Workspace preferences instead.

@lkoe Can you please enable Project -> Properties -> Java Code Style -> Formatter -> Enable project specific settings and then copy over your formatter settings from the workspace settings one by one (as far as I know there is no simple way to actually convert workspace preferences into project properties). The resulting jdt.core.prefs and jdt.ui.prefs should then be copied to all plugin projects and committed to git. That way every developer sees the same formatting rules.

**Comment by lkoe** [comment]
Done and merged.

**Comment by Bananeweizen** [comment]
BTW: You can have issues be closed automatically by using [keywords in the commit message](https://help.github.com/articles/closing-issues-using-keywords/). So instead of writing "issue #18 ..." you can write "fix #18 ..." and it will automatically close the issue when that commit gets merged to master.

You can see an example in my target platform change: https://github.com/Bananeweizen/eclipse-cs/commit/ad83fee08d2e77f3ada701838f13259a489e1f2d, where the "fix" keyword is dotted and has a tooltip explaining this.

**Comment by lkoe** [comment]
> BTW: You can have issues be closed automatically by using keywords in the commit message. So instead of writing "issue #18 ..." you can write "fix #18 ..." and it will automatically close the issue when that commit gets merged to master.

Great, thanks. That's pretty useful :-)
