### ISSUE TITLE
Eclipse Checkstyle Plugin 8.26 : illegal value 'import-control.xml' for property 'file'

### ISSUE THREAD

**Issue by Dichotomia** [checkstyle/eclipse-cs#188]
![image](https://user-images.githubusercontent.com/5593198/68680435-f0509180-0561-11ea-901d-6bc3028e7304.png)
Message: 
Checkstyle-Plugin: cannot initialize module TreeWalker - cannot initialize module ImportControl - illegal value 'import-control.xml' for property 'file'

Stack Trace:
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - cannot initialize module ImportControl - illegal value 'import-control.xml' for property 'file'
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:472)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:255)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:127)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:140)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:173)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module ImportControl - illegal value 'import-control.xml' for property 'file'
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:135)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:467)
	... 18 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: illegal value 'import-control.xml' for property 'file'
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:242)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:191)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:130)
	... 20 more
Caused by: java.lang.IllegalArgumentException: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: import-control.xml
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean$UriConverter.convert(AutomaticBean.java:338)
	at org.apache.commons.beanutils.BeanUtilsBean.convert(BeanUtilsBean.java:1079)
	at org.apache.commons.beanutils.BeanUtilsBean.convertForCopy(BeanUtilsBean.java:1095)
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:435)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:227)
	... 22 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: import-control.xml
	at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename(CommonUtil.java:517)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean$UriConverter.convert(AutomaticBean.java:335)
	... 26 more

**Comment by Dichotomia** [comment]
Checkstyle file:
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
	<module name="FileLength" />
	<module name="OrderedProperties"/>
	<module name="UniqueProperties" />
	<module name="TreeWalker">
		<module name="RegexpSinglelineJava">
			<property name="format" value="^\t* "/>
			<property name="message" value="Indent must use tab characters"/>
			<property name="ignoreComments" value="true"/>
		</module>
		<module name="AnnotationLocation" />
		<module name="AnnotationUseStyle" />
		<module name="AnonInnerLength" />
		<module name="ArrayTypeStyle" />
		<module name="AvoidNestedBlocks" />
		<module name="AvoidStarImport" />
		<module name="AvoidStaticImport" >
			<property name="excludes" value="org.torpedoquery.jpa.Torpedo.from,org.torpedoquery.jpa.Torpedo.select,org.torpedoquery.jpa.Torpedo.where,org.torpedoquery.jpa.TorpedoFunction.desc"/>
		</module>
		<module name="AtclauseOrder" />
		<module name="BooleanExpressionComplexity">
			<property name="max" value="4" />
		</module>
		<module name="CatchParameterName" />
		<module name="ClassTypeParameterName" />
		<module name="ConstantName" />
		<module name="CommentsIndentation" />
		<module name="CovariantEquals" />
		<module name="CustomImportOrder">
			<property name="customImportOrderRules" value="STATIC###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE"/>
			<property name="specialImportsRegExp" value="^org\."/>
			<property name="thirdPartyPackageRegExp" value="^com\."/>
			<property name="sortImportsInGroupAlphabetically" value="true"/>
			<property name="separateLineBetweenGroups" value="true"/>
		</module>
		<module name="CyclomaticComplexity" />
		<module name="DeclarationOrder" />
		<module name="DefaultComesLast" />
		<module name="EmptyBlock" />
		<module name="EmptyCatchBlock" />
		<module name="EmptyForInitializerPad" />
		<module name="EmptyForIteratorPad" />
		<module name="EmptyStatement" />
		<module name="EqualsAvoidNull" />
		<module name="ExecutableStatementCount"/>
		<module name="ExplicitInitialization" />
		<module name="IllegalCatch">
			<property name="illegalClassNames"
				value="java.lang.Throwable, Error, Throwable, java.lang.Error, Exception, java.lang.Exception" />
		</module>
		<module name="IllegalImport">
		  <property name="illegalClasses" value="java.io.File"/>
		</module>
		<module name="IllegalThrows" />
		<module name="IllegalToken" />
		<module name="IllegalTokenText" />
		<module name="IllegalType" />
		<module name="InnerAssignment" />
		<module name="InnerTypeLast" />
		<module name="InterfaceIsType" />
		<module name="InterfaceTypeParameterName" />
		<module name="InvalidJavadocPosition"/>
		<module name="ImportControl">
		  <property name="file" value="import-control.xml"/>
		</module>
		<module name="JavadocBlockTagLocation"/>
		<module name="JavadocMethod">
			<property name="validateThrows" value="true" />
			<property name="allowUndeclaredRTE" value="true" />
		</module>
		<module name="JavadocStyle">
			<property name="checkEmptyJavadoc" value="true" />
		</module>
		<module name="JavadocTagContinuationIndentation" />
		<module name="JavaNCSS" />
		<module name="LambdaParameterName" />
		<module name="LeftCurly">
			<property name="option" value="nl" />
			<property name="tokens" value="ANNOTATION_DEF, CLASS_DEF, CTOR_DEF, ENUM_CONSTANT_DEF, ENUM_DEF, INTERFACE_DEF, LITERAL_CASE, LITERAL_CATCH, LITERAL_DEFAULT, LITERAL_DO, LITERAL_ELSE, LITERAL_FINALLY, LITERAL_FOR, LITERAL_IF, LITERAL_SWITCH, LITERAL_SYNCHRONIZED, LITERAL_TRY, LITERAL_WHILE, METHOD_DEF, OBJBLOCK, STATIC_INIT" />
		</module>
		<module name="LeftCurly">
			<property name="tokens" value="LAMBDA" />
		</module>
		<module name="LocalFinalVariableName" />
		<module name="LocalVariableName" />
		<module name="MemberName" />
		<module name="MethodCount" />
		<module name="MethodLength"/>
		<module name="MethodName" />
		<module name="MethodParamPad" />
		<module name="MethodTypeParameterName" />
		<module name="MissingDeprecated" />
		<module name="MissingOverride" />
		<module name="ModifiedControlVariable" />
		<module name="ModifierOrder" />
		<module name="MultipleStringLiterals">
			<property name="allowedDuplicates" value="2" />
		</module>
		<module name="MultipleVariableDeclarations" />
		<module name="MutableException" />
		<module name="NeedBraces" />
		<module name="NoClone" />
		<module name="NonEmptyAtclauseDescription" />
		<module name="NoFinalizer" />
		<module name="NoLineWrap" />
		<module name="NPathComplexity" />
		<module name="OneStatementPerLine" />
		<module name="OneTopLevelClass" />
		<module name="OuterTypeFilename" />
		<module name="OuterTypeNumber" />
		<module name="OverloadMethodsDeclarationOrder" />
		<module name="PackageDeclaration" />
		<module name="PackageName" />
		<module name="ParameterAssignment" />
		<module name="ParameterName" />
		<module name="ParameterNumber">
			<property name="ignoreOverriddenMethods" value="true"/>
		</module>
		<module name="ParenPad" />
		<module name="RequireThis" />
		<module name="RedundantImport" />
		<module name="RedundantModifier" />
		<module name="RightCurly">
			<property name="option" value="alone" />
		</module>
		<module name="SimplifyBooleanExpression" />
		<module name="SimplifyBooleanReturn" />
		<module name="SingleSpaceSeparator" />
		<module name="StaticVariableName" />
		<module name="StringLiteralEquality" />
		<module name="SuperClone" />
		<module name="SuperFinalize" />
		<module name="SuppressWarnings" />
		<module name="ThrowsCount" />
		<module name="TrailingComment" />
		<module name="TypecastParenPad" />
		<module name="TypeName" />
		<module name="UnnecessaryParentheses" />
		<module name="UnnecessarySemicolonAfterTypeMemberDeclaration"/>
		<module name="UnnecessarySemicolonInEnumeration"/>		
		<module name="UnnecessarySemicolonInTryWithResources">
			<property name="allowWhenNoBraceAfterSemicolon" value="false"/>
		</module>		
		<module name="UnusedImports" />
		<module name="UpperEll" />
		<module name="VariableDeclarationUsageDistance">
			<property name="ignoreVariablePattern" value=".*stopwatch.*"/>
		</module>
		<module name="VisibilityModifier" />
	</module>
</module>

**Comment by Dichotomia** [comment]
import-control.xml:
<?xml version="1.0"?>
<!DOCTYPE import-control PUBLIC  "-//Checkstyle//DTD ImportControl Configuration 1.4//EN" "https://checkstyle.org/dtds/import_control_1_4.dtd">
<import-control pkg=".*" regex="true" strategyOnMismatch="allowed">
	<subpackage name="(beans|bean)">
		<disallow class="com.netappsid.framework.utils.ServiceLocatorProvider" />
		<disallow class="com.netappsid.framework.utils.ServiceLocator" />
	</subpackage>
	<subpackage name="(action|action|interface|interfaces|local|remote)">
		<disallow class="javax.ejb.TransactionAttribute" />
		<disallow class="javax.ejb.TransactionAttributeType" />
	</subpackage>
</import-control>

**Comment by romani** [comment]
Problem is with location of file, please try to use some absolute or relative path to diagnose issue

**Comment by Dichotomia** [comment]
It works with an absolute path. 
However it work in maven with 
				<plugin>
					<artifactId>maven-checkstyle-plugin</artifactId>
					<version>3.1.0</version>
					<dependencies>
						<dependency>
							<groupId>com.puppycrawl.tools</groupId>
							<artifactId>checkstyle</artifactId>
							<version>8.26</version>
						</dependency>
					</dependencies>
					<configuration>
						<configLocation>../checkstyle.xml</configLocation>
					</configuration>
				</plugin>
And our projects are :

![image](https://user-images.githubusercontent.com/5593198/68691682-6e1d9880-0574-11ea-86b6-566abb898386.png)

**Comment by romani** [comment]
Can you try './' in front of file name ?
I am not sure what is current folder for eclipse-cs

**Comment by lkoe** [comment]
Relative paths don't work for eclipse-cs, as the JVM work dir (from which relative paths are resolved) is the eclipse installation folder.
Instead you need to be using property placeholders to specify the location of additional files.
Read https://checkstyle.org/eclipse-cs/#!/properties

Depending on if your import control file is colocated with your Checkstyle configuration or located in the project folder you'd need to use `${config_loc}` or `${basedir}`. The maven plugin can also make use of those properties.

**Comment by lkoe** [comment]
Judging from your example project `${basedir}/import-control.xml` should work

**Comment by Dichotomia** [comment]
Ok thanks for the advice.
I works with in the pom.xml
```

			<plugin>
					<artifactId>maven-checkstyle-plugin</artifactId>
					<version>3.1.0</version>
					<dependencies>
						<dependency>
							<groupId>com.puppycrawl.tools</groupId>
							<artifactId>checkstyle</artifactId>
							<version>8.26</version>
						</dependency>
					</dependencies>
					<configuration>
						<configLocation>../checkstyle.xml</configLocation>
						<propertyExpansion>basedir=${project.basedir}/..</propertyExpansion>
					</configuration>
				</plugin>
```

And in the checkstyle.xml
	```
	<module name="ImportControl">
		  <property name="file" value="${basedir}/import-control.xml"/>
		</module>
```
