### ISSUE TITLE
No more warnings with 8.26.0.201911121319

### ISSUE THREAD

**Issue by heruan** [checkstyle/eclipse-cs#189]
Just updated to 8.26.0.201911121319 and I lost my checkstyle warnings. Do I have to perform any action after the update? Settings in Eclipse preferences seems fine, CS is active on the same projects as before, but I get no warnings when I should.

**Comment by romani** [comment]
Do you see something about plugin in eclipse logs ?

**Comment by heruan** [comment]
Nothing in the logs. I tried to use the built-in "Google Checks" and I got the warnings, it's just my own configuration which does not emit warnings anymore; it's weird since the configuration didn't change, it's the same that worked before the update.

The only difference I can spot it's my configuration is remote, but I tried to refresh/disable the cache without success. Any hint on how can I debug this?

**Comment by romani** [comment]
I can  suggest only experiments.
Upload some config on GitHub or any other remote and try. Try most simple checkstyle config - single rule.
Try config that has unexpected property name.
In all cases try run checkstyle manually on file through context menu .

**Comment by Bananeweizen** [comment]
You probably need to edit your configuration file. 8.26 has compatibility breaking changes (and some of the versions before, too). See also https://github.com/checkstyle/eclipse-cs/issues/190. I would copy the remote config to local and try to run standalone checkstyle with it. That should show the XML parser errors.

**Comment by Bananeweizen** [comment]
Closing due to missing feedback.
