### ISSUE TITLE
Missing built-in configuration (sun_check_eclipse.xml) from GUI

### ISSUE THREAD

**Issue by MMirabito** [checkstyle/eclipse-cs#202]
Dear all,  
My apologies in advance if this question was asked previously. 

I installed the latest version 8.28 of checkstyle using the  "**From an update site archive**"  technique see [here](https://checkstyle.org/eclipse-cs/#!/install).

When I was going through the instruction I am noticing that **sun_checks_eclipse.xml** is missing  from my options.

![image](https://user-images.githubusercontent.com/23298288/72257654-25b54200-35da-11ea-8248-0a0dc373b4c4.png)

However, when I look at advanced preferences [here](https://checkstyle.org/eclipse-cs/#!/preferences) it shows three options the GUI.
![image](https://user-images.githubusercontent.com/23298288/72258150-56e24200-35db-11ea-848b-c7736fde57d1.png)

Could anyone tell me what I might have done wrong.

Thanks in advance,
max

**Comment by rnveach** [comment]
@MMirabito Are you still having this issue with the newest version of eclipse-cs?

**Comment by MMirabito** [comment]
Hi @rnveach unfortunately I abandoned and since then i reimaged my machine 2 times .I am currently running the latest version of MyEclipse

Thanks
max

**Comment by rnveach** [comment]
Alright, thanks for the reply. I am going to close this. Feel free to re-open if you find this issue again.

**Comment by Calixte** [comment]
In version 7.3, built-in configurations started coming from the main checkstyle jar instead of the plugin itself.
Support for `sun_checks_eclipse.xml` was dropped. See ebbb85c04ef3991139054035236e6955a2683a7f.
The screenshot is just outdated.
