### ISSUE TITLE
plugin crashes eclipse when finds unsupported tag allowMissingThrowsTags

### ISSUE THREAD

**Issue by yilativs** [checkstyle/eclipse-cs#206]
plugin version throws 8.28.0.202001092018
crashes eclipse when finds non unsupported tag allowMissingThrowsTags

When checkstyle config contains allowMissingThrowsTags
e.g.

<module name="JavadocMethod">
      <property name="allowMissingThrowsTags" value="true" />
</module>

an exception is thrown:

allowMissingThrowsTags is 
!ENTRY net.sf.eclipsecs.core 4 0 2020-01-14 13:25:03.959
!MESSAGE Checkstyle-Plugin: cannot initialize module TreeWalker - cannot initialize module JavadocMethod - Property 'allowMissingThrowsTags' does not exist, please check the documentation
!STACK 0
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - cannot initialize module JavadocMethod - Property 'allowMissingThrowsTags' does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)

Crashing eclipse is bad idea even if this tag is no longer supported, please add proper exception handling that produces warning, e.g. found unsupported tag.

**Comment by Bananeweizen** [comment]
There have been lots of changes in how metadata is read, therefore this should not happen anymore in current versions.
