### ISSUE TITLE
Release 8.30?

### ISSUE THREAD

**Issue by Dichotomia** [checkstyle/eclipse-cs#219]
Hello,

The pull request for 8.30 has been integrated.

Any news about a new Eclipse plugin version?

Regards

**Comment by romani** [comment]
@Calixte , PR was https://github.com/checkstyle/eclipse-cs/pull/218
did you run release ? if not - please do.

**Comment by Calixte** [comment]
I did run the release script, but it fails when trying to push the changes and tags to the master branch. Am I missing some permissions to release?

**Comment by romani** [comment]
I did release ... works for me.

@Dichotomia , please try 8.30.0
