### ISSUE TITLE
DOCTYPE in configuration written wrong

### ISSUE THREAD

**Issue by holgergrote** [checkstyle/eclipse-cs#222]
If Eclipse-cs writes the configuration file it puts in the DOCTYPE:
DOCTYPE module PUBLIC "-//Checkstyle//DTD Check Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">
This is written in ConfigurationWriter.java:92
https://github.com/checkstyle/eclipse-cs/blob/1e08ad46046d65d702eaf08f98e404bbb9de6f77/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/ConfigurationWriter.java#L92

The Name shoud be:
DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">
see ConfigurationLoader.java:115 from checkstyle project

The difference ist the Word Checkstyle instead of Check.

Due to the wrong name the dtd is always loaded from that URL. So if the URL could not be retrieved (network problems, proxy settings, offline mode) the parsing fails and the complete Checkstyle does not work.

**Comment by romani** [comment]
fix is pushed to master withtout PR - https://github.com/checkstyle/eclipse-cs/commit/066c2398028904a571841c9815880d90fad803e5
