### ISSUE TITLE
upload eclipse-cs 8.35 to update-site

### ISSUE THREAD

**Issue by mickroll** [checkstyle/eclipse-cs#248]
The PR that resolved issue #243 bumped the checkstyle dependency to 8.35. Sadly, the plugin was not released for that version, like it was done for 8.34 with https://github.com/checkstyle/eclipse-cs/commit/96726c6138b70ec344e3c1393aedeffa9ec1e563

Please provide plugin version 8.35 on https://bintray.com/eclipse-cs/eclipse-cs/update-site

**Comment by romani** [comment]
@Calixte , please do
