### ISSUE TITLE
Wrong default scope setting for missing Javadoc causes eclipse-cs to ignore non-public methods

### ISSUE THREAD

**Issue by matthiasbasler** [checkstyle/eclipse-cs#252]
Found on eclipse-cs 8.35 (and likely 8.33 as well):

Since Checkstyle 8.20/8.21 the checks for missing method/type javadoc have been separated out be separate checks.
According to Eclipse-cs the default scope for these checks is "private" (**WRONG**). This means, that if the scope "private" is selected for either check in the configuration dialog, this scope information is not explicitly stored in the XML file, like this
```
<module name="MissingJavadocMethod"/>
<module name="MissingJavadocType"/>
```

Unfortunately, according to the [Checkstyle documentation](https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocMethod), the real default value for these checks is "public". This results in Checkstyle interpreting this configuration as requiring checks only for public methods. Private, default or protected methods are not checked.

Current workaround: Edit the XML configuration manually like this:
```
    <module name="MissingJavadocMethod">
      <property name="scope" value="private"/>
    </module>
    <module name="MissingJavadocType">
      <property name="scope" value="private"/>
    </module>
```
Then Checkstyle will correctly honor this scope.

The default scope in eclipse-cs has to be corrected for (at least) these two checks. Other checks might be affected as well.

**Comment by romani** [comment]
https://checkstyle.org/config_javadoc.html#MissingJavadocMethod

Eclipse-cs doesn't not control any Checks, all of them are part of https://github.com/checkstyle/checkstyle so all suggestions should be opened in library project.

Unfortunately such Checks are very old, and change of default value is breaking compatibility, so we unlikely to do this, as it will be damage for a lot of configs in the world.

Default is selected by usually most acceptable behavior, but it always need to be adjusted to current team demands and culture.
Do not hesitate to customize Checks, default behavior is likely be not enough.
