### ISSUE TITLE
"org.example" couldn't be resolved in MetadataFactory.java

### ISSUE THREAD

**Issue by bzeng** [checkstyle/eclipse-cs#255]
eclipse-cs/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java

Seems like the package couldn't be found, so line 64 to 66 is causing compilation errors after importing the projects to eclipse

**Comment by Calixte** [comment]
You should run `./build-metafile-gen.sh` and refresh to get the missing jar.

**Comment by bzeng** [comment]
OK thanks!
