### ISSUE TITLE
Checkstyle-Plugin: unable to parse configuration stream

### ISSUE THREAD

**Issue by publicjoe62** [checkstyle/eclipse-cs#271]
Hello,

I'm using eclipse 2020-6 and 2020-9 on several computers. I'm using checkstyle

![image](https://user-images.githubusercontent.com/15066755/96758793-837f8180-13d7-11eb-83fa-0fd2ac579ad8.png)

On each computer I copied the google style check and make it to default and assign it to my project.

![image](https://user-images.githubusercontent.com/15066755/96759043-cd686780-13d7-11eb-9153-8e3cd77db8b7.png)

Then executing style check results in an error 

![image](https://user-images.githubusercontent.com/15066755/96758467-1835af80-13d7-11eb-851c-ce1b005ffa08.png)

Any ideas?

Thanks and Greetings
Hannes

**Comment by rnveach** [comment]
> On each computer I copied the google style check 

Where did you copy it from and what is it's contents? Why do you need to bring this copy when there is a built-in google right below your copy?

**Comment by romani** [comment]
in exception there should be "Caused by" block and it should have more details on what is wrong.
if no details , please recheck that xml is in general valid form.

**Comment by publicjoe62** [comment]
Hi there,

I found a solution. If I copy the google_check.xml into my working directory and link it as "external" it works.

Thank you for supporting. Have a nice weekend.

Greetings
Hannes
