### ISSUE TITLE
[question] How to find suppressions.xml inside jar to match mvn behaviour?

### ISSUE THREAD

**Issue by space88man** [checkstyle/eclipse-cs#272]
Why can Eclipse-CS find the configuration inside jar-on-classpath, but then cannot find suppressions.xml using the same technique?

Update TL;DR: It turns out the reason checkstyle can find the configuration file is it is provided by Eclipse-CS as a jar-URI `jar:file:/.../wildfly-checkstyle-config-1.0.8.Final.jar!/wildfly-checkstyle/checkstyle.xml`. However, since the jar is not on the classpath, subsequently the SupressionFilter search for `/wildfly-checkstyle/suppression.xml` fails. OTOH maven uses a plugin dependency to put the jar on the classpath.

Edit: Eclipse 2020-09 with 8.35.0 of Eclipse-CS

Wildfly uses a jar, wildfly-checkstyle-config.jar, containing the configuration file:

```
# config file references suppression XML...
    <module name="SuppressionFilter">
        <property name="file" value="/wildfly-checkstyle/suppressions.xml" />
    </module>

# Wildfly pom.xml configuration:
<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${version.checkstyle.plugin}</version>
                    <configuration>
                        <configLocation>wildfly-checkstyle/checkstyle.xml</configLocation>
                    </configuration>
```

At the console, the maven-checkstyle-plugin finds `wildfly-checkstyle/checkstyle.xml`, and `wildfly-checkstyle/suppressions.xml` from the jar-on-classpath.

Eclipse-CS finds the configuration file from the jar, but then cannot find the suppressions file; it appears that it is looking for a filesystem path `/wildfly-checkstyle/suppressions.xml`. Can we configure Eclipse-CS to also try classpath resource resolution for `suppressions.xml`. 

Note: I have tried modifying the Wildfly pom.xml with `${samedir}suppressions.xml` and then tellling Maven with `<propertyExpansion>samedir=/wildfly-checkstyle/</propertyExpansion>`. This hack does work, but I would prefer to not touch Wildfly as their configuration is distributed as a  Maven central artifact.

References:
1. Wildfly checkstyle configuration: https://github.com/wildfly/wildfly-checkstyle-config/blob/master/src/main/resources/wildfly-checkstyle/checkstyle.xml
1. Wildfly checkstyle configuration: https://github.com/wildfly/quickstart/blob/4d927366c48d9c02b0397f65eaa28f7a1ca4fc3c/pom.xml#L236

**Comment by space88man** [comment]
From the documentation, it seems this should work, and cs should get `suppressions.xml` from the classpath:

> Location of the file defined in file property is checked in the following order:
>
>    as a filesystem location
>    if no file found, and the location starts with either http:// or https://, then it is interpreted as a URL
>    if no file found, then passed to the ClassLoader.getResource() method.

**Comment by rnveach** [comment]
> Why can Eclipse cs find the configuration inside jar-on-classpath, but then cannot find suppressions.xml using the same technique?

I am no way familar with how eclipse handles plugin JARs or Eclipse-CS itself.

But this sounds like Eclipse-CS may have access to a class loader that allows it to load the files from other JARs and checkstyle, which actually does the suppression file loading does not. I assume eclipse does some blocking off so plugins aren't naturally aware of other plugins, similar to how android tries to behave for security.

Checkstyle recently (within the past year I believe) disallowed receiving custom class loaders and it has to use it's own to load the files demanded by the configuration. An easy way to confirm if this is the issue, you can find a version of Eclipse-CS that still had this removed functionality and see if it will load the suppression there.

@romani ping

**Comment by romani** [comment]
https://checkstyle.org/config_filters.html#SuppressionFilter

>  Location of the file defined in file property is checked in the following order:
    as a filesystem location
    if no file found, and the location starts with either http:// or https://, then it is interpreted as a URL
    if no file found, then passed to the ClassLoader.getResource() method.

Eclipse-cs does not do any special logic for resources to find. Whole logic is in checkstyle library, but it depends on search in classpath that plugin set. 
Classpath is defined before execution of checkstyle, strange that config is found in wildfly-checkstyle-config.jar but suppression xml is not found from the same jar.

**Comment by space88man** [comment]
If I use the `value="wildfly-checkstyle/suppressions.xml"`, the situation becomes worse, even mvn cannot find the file:

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: wildfly-checkstyle/suppressions.xml
    at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename (CommonUtil.java:520)
    at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppressions (SuppressionsLoader.java:218)
    at com.puppycrawl.tools.checkstyle.filters.SuppressionFilter.finishLocalSetup (SuppressionFilter.java:264)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure (AutomaticBean.java:194)
    at com.puppycrawl.tools.checkstyle.Checker.setupChild (Checker.java:468)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure (AutomaticBean.java:198)
    at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:168)
    at org.apache.maven.plugins.checkstyle.AbstractCheckstyleReport.executeReport (AbstractCheckstyleReport.java:533)
    at org.apache.maven.plugins.checkstyle.CheckstyleReport.executeReport (CheckstyleReport.java:57)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:255)
 ```

**Comment by space88man** [comment]
I have a slightly clearer understanding of the problem to solve now:

Problem: how to find `/wildfly-checkstyle/suppressions.xml` inside a jar; needed is the the equivalent of  Maven's plugin dependencies 

The lifecycle mapper converts the configuration-file-inside-jar to a Remote Configuration
```
jar:file:/home/vagrant/.m2/repository/org/wildfly/checkstyle/wildfly-checkstyle-config/1.0.8.Final.....
```
This enables Eclipse-CS to point checkstyle to the correct location but there is no equivalent of maven's plugin dependencies, so there is no wildfly-checksytyle-config jar on the classpath hence checkstyle via Eclipse-CS does not find `/wildfly-checkstyle/suppressions.xml`.

Is there a way to achieve this in Eclipse-CS .

Recap: the suppressions file is referenced as `/wildfly-checkstyle/suppersions.xml` inside the configLocation.  checkstyle-via-maven-checkstyle-plugin finds it as maven has wildfly-checkstyle-config as a plugin dependency.
