### ISSUE TITLE
bintray will shut down - update site needs to be moved

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#279]
The plugin is currently hosted on bintray, which is going to be terminated: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

-----

Hi Roman,

Thank you for supporting JFrog through your use of Bintray. We are and continue to be a community-focused company, and in the spirit of transparency we’re giving you advance notice that as of May 2021, we will be sunsetting Bintray.

Many of the services that Bintray provides are now served by the JFrog Platform and this sunset allows us to focus our development and innovation efforts on building a comprehensive end-to-end solution for hosting and distribution of software artifacts.

To help minimize any potential disruption in service, we have several solutions for you to employ during this transition period to keep your project running smoothly. Below are details on who is affected, how to mitigate any disruption and additional resources for you to contact if you encounter any snags along the way.

Repositories Hosted on Bintray
Your repositories for module types including Docker, Maven (Java), Npm, NuGet, RPM, Vagrant, and Generic will need to be migrated off of Bintray service on or before May 1st to avoid any disruption in service.
Conan OSS Users
Conan packages for C/C++ have been migrated to ConanCenter.

**Migrate to the Free Subscription of Artifactory**

JFrog has a new free subscription tier that gives you the ability to manage and distribute artifacts with automated security scanning. You can sign up for a free subscription http://mkto-lon040102.com/n/yxNFt8oE0403ZNu00000010 and start migrating your Bintray artifacts. Unlike Bintray, this service also offers Continuous Integration and is suitable for hosting CI artifacts, such as Snapshot builds.​
For additional details, please read the community announcement http://mkto-lon040102.com/n/AN0100FN10E4xo80030v0tZ .

JFrog wants to thank you again for your continued support. We’re committed to our community and strengthening our offerings. Other questions? Please feel free to contact us on Twitter 

Best Regards,
JFrog Team

**Comment by lkoe** [comment]
That's a proper kick in the groin 😬 
Anyone know good alternatives for hosting binaries/p2 repos?

Maven Central is not an option as because p2 repos work with Maven GAV coordinates.
Sourceforge was to unreliable - thats why we migrated to bintray in the first place.
Github pages isn't really meant to host large binaries.
...

**Comment by Bananeweizen** [comment]
Looking at all the plugin URLs that I have in different Oomph setups, the order of occurrences is
* eclipse.org
* github.io
* project's own website
* sourceforge

Since I see at least 10 plugins hosted at github, I'm wondering if that is really a problem.

**Comment by romani** [comment]
github.io changed a lot in last few years, it might be ok to try again, especially if we have no choice :).

**Comment by lkoe** [comment]
Github pages would work in principle, however would require to commit the binary artifacts for the update site(s) into the gh pages git repo. Repo size and traffic limits are cause for concern.

AWS S3 can certainly also used to server those files, but I don't know which conditions apply there.

Eclipse Marketplace lists about 4500 installs (via marketplace) in the last 30 days. Lets assume additional 1500 installs directly from the update site (without involving marketplace).
That's 6000 installs by roughly 25 MB, totalling nearly 150 GB traffic per month, if I am not mistaken.

As for storage, currently bintray hosts 35 different releases as update site. That's nearly 1 GB of storage capacity needed.
However, it's possible to de-publish old update sites and require users to download them as archive from the gh releases.

**Comment by romani** [comment]
I updated issue description with email content that I got from jfrog.

>Migrate to the Free Subscription of Artifactory

Can it be option for us ?

**Comment by lkoe** [comment]
If I understand correctly free subscription allows you to deploy artifactory to aws/google/azure cloud.

So, technically, yes - you can surely host P2 update sites on artifactory.
However I'd assume that traffic/processor restrictions of AWS still apply. Do you have an idea, where the limits are there?

**Comment by Calixte** [comment]
It says "10GB Transfer/month" on this page: https://jfrog.com/pricing/ which I think is not enough according to your previous estimate.
They do have an OSS section on their website with a "cloud" version coming soon.

> JFrog Provides Free Artifact Management, Security and CI/CD Tools for OSS Projects
> This program will be active very soon. To be notified when you’ll have access to these free tools, Please contact us.

**Comment by lkoe** [comment]
Indeed https://jfrog.com/open-source/ (Artifactory Cloud for OSS) seems interesting. I subscribed for notification as it becomes available.

Prerequisites listed are:
>Popular with an active community.
>Pure Open Source with no current or planned commercial activity around it.
>Willingness to mention JFrog’s contribution on your project’s home page.

The third point would need to be adressed, if we should go with this option

**Comment by Bananeweizen** [comment]
This gradle plugin was just mentioned in a tweet regarding the JCenter removal to simplify publishing to maven central: https://github.com/gradle-nexus/publish-plugin/. I have never used it myself, so I cannot judge if it would make the publishing easier. @lkoe maybe you want to investigate it.

**Comment by Bananeweizen** [comment]
For github pages there is also this tutorial: http://www.lorenzobettini.it/2021/03/publishing-an-eclipse-p2-composite-repository-on-github-pages/

**Comment by romani** [comment]
@Bananeweizen , @lkoe , do you know how all other Eclipse plugins host their binaries ?

**Comment by lkoe** [comment]
I checked a few, some (TestNG, PMD) are also still on bintray, others seem to be on GH-Pages (Cucumber).
Other popular plugins are mostly with company ties and can afford their own hosting.

It seems for the time being Github pages would be the best alternative, at least until Artifactory Cloud for OSS program has launched.

**Comment by mak-42** [comment]
It seems they switched bintray off. It impossible to install the plugin now :(

**Comment by Pontesegger** [comment]
Github is a fine place to host. Did it also for EASE, and works like a charm. When manually deploying this can be done in a few minutes. See Lorenzos Blog for details how to set up:
http://www.lorenzobettini.it/2021/03/publishing-an-eclipse-p2-composite-repository-on-github-pages/

**Comment by gregdyke** [comment]
The repository URL following Calixte's change appear to be http://checkstyle.org/eclipse-cs-update-site/

**Comment by dhendriks** [comment]
When I use Oomph to install it, I see the following in the log:

```
Fetching compositeArtifacts.xml from http://checkstyle.org/eclipse-cs-update-site/
Fetching compositeArtifacts.xml from http://checkstyle.org/eclipse-cs-update-site/updates/8.x/
Fetching compositeArtifacts.xml from http://checkstyle.org/eclipse-cs-update-site/updates/8.x/8.41.x/
Fetching artifacts.xml.xz from http://checkstyle.org/eclipse-cs-update-site/releases/8.41.0.202105041735/ (1.5kB)
```

It thus seems there are version-specific update sites contained in composite update sites.

**Comment by dhendriks** [comment]
The new update site works for me.

**Comment by romani** [comment]
@Calixte, should we close this PR ?

**Comment by breuniga** [comment]
> The new update site works for me.

The update site works for me, too. But I'm not able to specify a version as mentioned in the README.md.
Example https://checkstyle.org/eclipse-cs-update-site/8.41.0/ does not work for me.

**Comment by dhendriks** [comment]
> Example https://checkstyle.org/eclipse-cs-update-site/8.41.0/ does not work for me.

See my earlier comment. Use these URLs:

- http://checkstyle.org/eclipse-cs-update-site/
- http://checkstyle.org/eclipse-cs-update-site/updates/8.x/
- http://checkstyle.org/eclipse-cs-update-site/updates/8.x/8.41.x/
- http://checkstyle.org/eclipse-cs-update-site/releases/8.41.0.202105041735/

I would of course be really great if the update site was browsable in a browser, to make it easier to find the correct URLs. Especially for a specific version, as the date/time is otherwise difficult to guess for a next version.

**Comment by breuniga** [comment]
@dhendriks many thanks, that worked for me 👍
So I think the `README.md` needs to be updated

**Comment by nkavian** [comment]
How do we access sevntu now? None of those URLs work and it's not found in the `checkstyle` update site either. I've spent hours trying to figure out why I can't access it. Please help.

**Comment by dhendriks** [comment]
> How do we access sevntu now? None of those URLs work and it's not found in the `checkstyle` update site either. I've spent hours trying to figure out why I can't access it. Please help.

My May 17 comment shows URLs that I've been using ever since. They work well for me. In particular the ones of the form http://checkstyle.org/eclipse-cs-update-site/updates/8.x/8.41.x/. Do they not work for you?

**Comment by nkavian** [comment]
That only provides the Checkstyle plugin for Eclipse. I'm looking for the SevNTU add-on: https://sevntu-checkstyle.github.io/sevntu.checkstyle/

![image](https://user-images.githubusercontent.com/1127421/130254792-2afb7363-58d9-47aa-a504-312379421611.png)

**Comment by Bananeweizen** [comment]
Closing. The new update site works well, and the sevntu problem has been moved to a separate issue.

Anyone trying to check whether a website is a valid update site or not: Please don't use the browser for that. Rather use the "Repository explorer" view in eclipse (which comes with the "Oomph Setup" feature. That one works like the update manager and tells you whether some URL is a valid update site or not.

**Comment by ChrisGWarp** [comment]
Did anyone give any thought to providing the older versions?
