### ISSUE TITLE
Plugin Compatibility with Eclipse running on Java 16

### ISSUE THREAD

**Issue by jorsol** [checkstyle/eclipse-cs#281]
Java 16 comes with [JEP 396](https://openjdk.java.net/jeps/396): Strongly Encapsulate JDK Internals by Default

When using Java 16 in Eclipse the plugin fails with:
```
Errors occurred during the build.
Errors running builder 'Checkstyle Builder' on project 'common'.
Unable to make field private static volatile java.net.Authenticator 
java.net.Authenticator.theAuthenticator accessible: module java.base does not 
"opens java.net" to unnamed module @5cfdefb7
```

**Comment by romani** [comment]
please open ticket at https://github.com/checkstyle/checkstyle/
plugin just do integration with Eclipse, no logic on parsing and validation, all this logic is in library.
Library is updated to support only up to jdk14 syntax :(.

**Comment by jorsol** [comment]
Hi @romani, sorry if I was not clear, but the issue is "running" Eclipse with Java 16 as runtime (not with the parsing or validation of Java 16 syntax), so yes this is related to the plugin integration with Eclipse. I point out the JEP 396 since that JEP enables the encapsulation of JDK internals and this plugin makes a **hack** around `java.net.Authenticator` wich triggers the error.

https://github.com/checkstyle/eclipse-cs/blob/4ae6d81063d2328d70060a66f3590dd9f2c5c4c3/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/RemoteConfigurationType.java#L372-L380

Just as a suggestion, recent versions of Eclipse (since Eclipse 4.17 (2020-09)) requires Java 11 as minimum, so this plugin could probably make use of the new HTTP Client of Java 11 instead of hacking around `HttpURLConnection`.
