### ISSUE TITLE
Cannot install plugin in Eclipse

### ISSUE THREAD

**Issue by thudofortna** [checkstyle/eclipse-cs#291]
When I try to install this plugin using Eclipse Marketplace, it is said that: No repository found at https://dl.bintray.com/eclipse-cs/eclipse-cs/8.40.0/.

When I follow this download link in checkstyle.org: https://bintray.com/eclipse-cs/eclipse-cs/update-site-archive/_latestVersion, it is shown as 404 not found

According to this: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/  the download link in bintray has been taken away.

Now, how can I install this plugin for Eclipse?

**Comment by BigDada1** [comment]
It seems, that [Bintray is down](https://bintray.com/): *Thanks for supporting Bintray! This service has now been sunset, and to assist with migration to the JFrog Platform, paid accounts can login until July 4th.*

**Comment by Calixte** [comment]
Can you try again from the Eclipse Marketplace? I updated the repository URL.
You can also try the Update Site URL directly using "Install New Software...": http://checkstyle.org/eclipse-cs-update-site/

**Comment by thudofortna** [comment]
I tried again in Eclipse Marketplace and it worked! Thank you.
