### ISSUE TITLE
https://checkstyle.org/eclipse-cs/update/ update is down?

### ISSUE THREAD

**Issue by cleforwen** [checkstyle/eclipse-cs#294]

**Comment by Pontesegger** [comment]
see https://github.com/checkstyle/eclipse-cs/issues/279

**Comment by Calixte** [comment]
New URL is https://checkstyle.org/eclipse-cs-update-site/

**Comment by ChrisGWarp** [comment]
I'm sorry, but this makes no sense to me at all.
The old update site was: https://checkstyle.org/eclipse-cs/update
The new update site is: https://checkstyle.org/eclipse-cs-update-site
A) What has this got to do with JFrog shutting down bintray.com?
B) Why (as it's broken all of my automation) could the same URL not have been reused? A simple URL rewrite rule should have fixed that.
