### ISSUE TITLE
Update filter icon of Checkstyle to the latest Eclipse filter icon

### ISSUE THREAD

**Issue by vogella** [checkstyle/eclipse-cs#304]
Would you accept a PR which updates the Checkstyle filter icon to the latest from the Eclipse platform?

![image](https://user-images.githubusercontent.com/139910/127615584-4e8bddd9-8756-4c87-b217-c6eb1ce923f9.png)

**Comment by rnveach** [comment]
@vogella Is there a way to hook into what Eclipse uses itself or it has to be a direct PNG?

**Comment by romani** [comment]
@Calixte , please approve issue.

I am ok, with new images.
