### ISSUE TITLE
Update help icon in preference to use png files

### ISSUE THREAD

**Issue by vogella** [checkstyle/eclipse-cs#305]
The current help icons of the Preference page look bad in the dark theme. I guess they are still gif files.

![image](https://user-images.githubusercontent.com/139910/127615868-5813f74c-074c-4ceb-bb3b-ad45d2c37be8.png)

Would you accept a PR for updating the icons to png files?

**Comment by rnveach** [comment]
@vogella I can't speak for other admins, but I am willing to look at a PR to update the PNGs. Be warned that you have to support many different flavors of Eclipse as not everyone uses the same version or the same theme.

**Comment by romani** [comment]
I would use icons from latest icons set of eclipse.

@Calixte , please share your position on this

**Comment by Calixte** [comment]
Does anyone know if we have to ship our own icons with the plugin, or if we can use the ones from the current theme?

**Comment by romani** [comment]
I have no idea. Either is fine for me.
