### ISSUE TITLE
"Expected an @return tag."

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#31]
I just have that issue in a local workspace and I would argue it is not correct grammar, since most people will not speak the "at". I suggest to remove the "an" completely, since it would then match the similar message "Expected @param tag for foo..." and avoids the problem of a/an.

**Comment by lkoe** [comment]
That's a checkstyle violation you're referring to?
Those message texts are generated from Checkstyle core, so it would need to be fixed there.

**Comment by Bananeweizen** [comment]
Ah, that's why I did not find it immediately via file search. I just thought that all of those would be generated by the custom check messages feature of eclipse-cs.
