### ISSUE TITLE
NeedBracesCheck: Quickfix is broken since 8.36.1

### ISSUE THREAD

**Issue by rnveach** [checkstyle/eclipse-cs#315]
Since 8.36.1, you can no longer do a quick fix on `NeedBracesCheck` violations in the problem view. Quick fix is completely grayed out and does nothing when clicking.

Confirmed by installing 8.35 , verifying quick fix works, resetting eclipse (from pre-Checkstyle install save), installing 8.36.1, verifying quick fix does not work. Both versions showed the same checkstyle error after doing a clean build.

Input file:
````
package test;

/** Main. */
public class Main {
  /** main. */
  public static void main(String[] args) {
    // if (true)
    // System.out.println("test");
    if (true)
      System.out.println("test");
  }
}
````

Configuration: Google checks.

**Comment by rnveach** [comment]
I am assuming all quick fixes are now not working.

8.36.1 still has the XML files that detail the quick fix classes that made it work in 8.35. The only difference should be the inclusion of checkstyle's meta data.

I am assuming this is happening because the meta data from checkstyle is taking priority over anything else that is imported. Since checkstyle has no clue about quick fixes, it is defaulting to `null` (no quick fix available) and leaving it as that with no type of merging.

**Comment by rnveach** [comment]
@romani @Calixte @lkoe Does eclipse-cs have support for 3rd party quick fixes like sevntu or is it only what is in eclipse-cs?
I am not seeing any quick fixes in sevntu but wanted to confirm if eclipse-cs had the support.

**Comment by Calixte** [comment]
We first noticed this here: https://github.com/checkstyle/eclipse-cs/pull/286#discussion_r619450042
The metadata project intent was to have this ability to merge metadata from checkstyle with custom metadata (quickfixes) from the plugin, but as you noticed, it doesn't work right now.

> Does eclipse-cs have support for 3rd party (like sevntu) quick fixes where the code is in the other library?

I don't know, though I see no reason why we wouldn't be able to support that.

**Comment by rnveach** [comment]
Thanks. I am assuming as long as the classpath is in the old XML file, and it can be instantiated, quickfixes can be access from a 3rd party library.

That makes restoration a bit trickier. We want to continue to support users adding new quickfixes, but it doesn't really make sense to be given a partial XML file in checkstyle's case with only the quickfix information.

It sounds like we need something new.

**Comment by romani** [comment]
Quick fix is possible only when you/plugin know how it works, it might for standard set of Checks but not third-party

, this is why we have big future project for Checkstyle to create auto fix possibilities for each Check.

**Comment by rnveach** [comment]
@romani We can discuss this more when checkstyle starts to work on that project, but it would be a good idea to keep this project in mind when it does. Eclipse users have an option to click on warning and do a "Quickfix" to resolve it. It would be great if things can be made so that eclipse-cs can also hook into that functionality to provide it to eclipse-cs users too. Then we aren't duplicating things and becoming more uniformed.

**Comment by romani** [comment]
Yes, meanwhile, eclipsecs can have their own quick fix logic.
