### ISSUE TITLE
Eclipse marketplace identifies that 8.4.4 does not work with eclipse 2021-06 or 2021-09

### ISSUE THREAD

**Issue by marioja** [checkstyle/eclipse-cs#328]
Nothing in the release notes identified that.  Is this an eclipse marketplace configuration issue or is eclipse-cs 8.4.4 not compatible after eclipse 2021-03?

**Comment by romani** [comment]
please try latest version, I am not sure it will resolve a problem, but at least we get know how it works on latest.
We do not support old versions of checkstyle, all changes appear in latest releases.

**Comment by Calixte** [comment]
It's just an Eclipse Marketplace configuration issue. I've fixed it.
