### ISSUE TITLE
can't install 8.7 version on Eclipse Oxygen

### ISSUE THREAD

**Issue by noelo-cohelo** [checkstyle/eclipse-cs#34]
I'm trying to install via Eclipse Marketplace.

Artifact not found: https://dl.bintray.com/eclipse-cs/eclipse-cs/8.7.0/plugins/net.sf.eclipsecs.checkstyle_8.7.0.201801170708.jar.

**Comment by lkoe** [comment]
Sorry, seems I broke the site experimenting with automated bintray deployment. Should now work again.

**Comment by noelo-cohelo** [comment]
Yes, now it's ok. Thank you very much for such fast response! :)

**Comment by Bananeweizen** [comment]
Ah, that also fits with an update error I saw this morning. I was already expecting new issues with our company proxy and bintray, since those had some conflicts in the past...
