### ISSUE TITLE
Requirements are inconsistent regarding Java 11

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#348]
In #340 EclipseCS was upgraded in parts to be aligned with the Checkstyle 10.0 Java 11 requirements. Some parts of that don't look correct to me:
* the minimum required Eclipse version should be 2020-09, since that is the first to require Java 11 as runtime. See https://wiki.eclipse.org/Eclipse/Installation
* bundles should use Java 11 compiler compliance settings instead of 8 (right now, only their classpath is set to use the 11 runtime)
* the eclipse feature should require org.eclipse.core.runtime 3.19 or later (since that is the bundle version in 2020-09), otherwise the feature can still be installed into older versions and will break after restart only.

**Comment by Calixte** [comment]
@Bananeweizen Do you want to open a PR for 470031f?

**Comment by Calixte** [comment]
Never mind, it's #349.

**Comment by rnveach** [comment]
@Calixte @Bananeweizen Is this issue now resolved?

**Comment by Bananeweizen** [comment]
Looks good now. If I find anything else, I'll raise separate issues or PRs. Thanks
