### ISSUE TITLE
Activate Checkstyle for whole Eclipse workspace

### ISSUE THREAD

**Issue by lrozenblyum** [checkstyle/eclipse-cs#356]
It would be nice to be able to activate Checkstyle on the whole Eclipse workspace (e.g. via the workspace's Checkstyle settings).

Motivation: having a workspace with 200+ project in it makes it complex to enable it per project.
Intellij IDEA plug-in looks to be activate by default for all.

**Comment by Bananeweizen** [comment]
You can at use multi select, properties, checkstyle, blueprint.

**Comment by lrozenblyum** [comment]
Thanks @Bananeweizen for the suggestions. They look to be solving the problem.
