### ISSUE TITLE
Unable to Install in Eclipse

### ISSUE THREAD

**Issue by garberfc** [checkstyle/eclipse-cs#363]
I'm attempting to install the CheckStyle plug-in from the Eclipse Marketplace, but it errors out with the message:
**Unable to read repository at https://checkstyle.org/eclipse-cs-update-site/content.xml.
Stream already closed**

**Comment by romani** [comment]
Can you share screenshot of problem ?

**Comment by garberfc** [comment]
**Here's the screenshot from the Eclipse Marketplace:**
![image](https://user-images.githubusercontent.com/6155463/187675502-9e9d5aeb-4c19-4965-9c54-4c3c2cf4edc0.png)

**And the web page:**
![image](https://user-images.githubusercontent.com/6155463/187675704-d8b0fe68-249d-4cf4-94b0-1ab87e20cfaf.png)

**Comment by romani** [comment]
@rnveach , do you have such problem?

**Comment by garberfc** [comment]
Yes, I'm still have the problem. I think it's just a matter of the content.xml file missing from the server.

**Comment by garberfc** [comment]
Here's the version info on the version of Eclipse I'm using:
Version: 2022-06 (4.24.0)
Build id: 20220609-1112

I've been able to install other software from the Marketplace like "Eclipse Web Developer Tools 3.26". 

I just attempted to install CheckStyle again, and it's still failing with the same message.

**Comment by rnveach** [comment]
I installed Eclipse 2022-06 for Enterprise Java and Web Developers and was able to install Checkstyle from the market place and from the URL.

Are you sure you trusted the plugin during the installation process? Can you try with a clean Eclipse download/install?

**Comment by garberfc** [comment]
The installation is just a few days old. Very little was added / modified.

-- Where are the eclipse log files stored? I searched under \eclipse\*.log and *error*.* and didn't find any files. I also looked in the Windows Event Viewer. I didn't note anything.

**Comment by rnveach** [comment]
> Where are the eclipse log files stored?

Window > Show View > Other - Select "Error Log".

> The installation is just a few days old. Very little was added / modified.

At this point, it is looking like it is something on your end. I am not about to reproduce any issues. The release is about 4 months old, so if it was a global issue, I would think we would have seen more reports by now.

Besides a clean installation, the only other thing I can think of is to check if your internet or any proxy is preventing working with the update site properly.

**Comment by rnveach** [comment]
I found this while googling: https://www.eclipse.org/forums/index.php/t/1108948/ . Last part has the solution to their issue.

> I've been able to install other software from the Marketplace like "Eclipse Web Developer Tools 3.26".

Was that installation done through HTTP or HTTPS?

**Comment by garberfc** [comment]
Oh, that error log. Here's the results:
![image](https://user-images.githubusercontent.com/6155463/187767679-a5d06ff5-46e4-4b1a-b237-11b08da2b102.png)

I added the lines to my eclipse.ini. No luck.

Though, when I started eclipse I'm seeing the following in the log:
![image](https://user-images.githubusercontent.com/6155463/187768784-f88ba8cf-7fc4-46a8-8029-3c0efe2adf37.png)

Here are my proxy settings. Do you see any issues:
![image](https://user-images.githubusercontent.com/6155463/187768978-4b007d31-f39a-45fd-bf08-b3308ab12db2.png)

**Comment by rnveach** [comment]
I see errors related to https://checkstyle.org/eclipse-cs-update-site/p2.index which is an actual file that exists. I do not get any similar errors. You can try testing in your browser.

Since you are using a proxy, I think its safe to assume this has something to do with your internet connection to the website. It seems it is not "failing" on retrieving the p2 index, but it is failing on what I assume is the backup method, content.xml .

You can try disabling the proxy, if possible and checking, but I won't be able to assist you anymore.

**Comment by garberfc** [comment]
As recommended I broke down and did a clean install. After the install I was able to install CheckStyle. I wish knew why it wouldn't install...

Thanks for all the help!

**Comment by Bananeweizen** [comment]
Just as a note for future repetitions: Don't be confused by the browser giving a 404 when browsing p2 update sites. The browser will try to show an index.html, which simply doesn't exist. Still, all the files required for an update site are there, the browser just doesn't list them, because github disables directory listings.
