### ISSUE TITLE
config file doesn't work for building nested module

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#390]
Running maven on the root is fine, but it does not work for modules separately due to wrong relative file paths.
```
cd net.sf.eclipsecs.core
mvn verify
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:check (checkstyle-check) on project net.sf.eclipsecs.core: Failed during checkstyle configuration: cannot initialize module SuppressionFilter - Unable to find: config/suppressions.xml
```
Is there a solution for that problem in the other checkstyle repositories maybe? I see a basedir variable in the comments of the main checkstyle project config, but that seems unused, since there are no multiple maven modules there, right?

**Comment by romani** [comment]
Other repositores are single module.
Maybe there we have multimodules https://github.com/sevntu-checkstyle/sevntu.checkstyle

But they are not actually bound by parent pom much

**Comment by rnveach** [comment]
> basedir variable in the comments of the main checkstyle project config

This only assists with printing violations as I recall. It is not used for where to pull in files from. We rely only on file paths being passed to us.
See https://checkstyle.org/config.html#Checker_Properties

> it does not work for modules separately due to wrong relative file paths

This is a maven-checkstyle-plugin issue and I think it has been reported with no fix for a while. I think the only way around it currently is to specify absolute paths, which would not work for different wordwide contributors and a CI environment.
