### ISSUE TITLE
can't install on Eclipse Oxygen

### ISSUE THREAD

**Issue by noelo-cohelo** [checkstyle/eclipse-cs#43]
HTTP Server 'Service Unavailable': http://eclipse-cs.sourceforge.net/update/content.xml

HttpComponents connection error response code 503.

**Comment by Bananeweizen** [comment]
The update site URL works fine. It is using compositeContent.xml instead, not sure why you want to read the above (not existing file).

**Comment by noelo-cohelo** [comment]
It' not that **I** want :)
It seems that Eclipse is just trying to do that during installing through marketplace...

**Comment by Bananeweizen** [comment]
In that case, only @lkoe can check, due to access rights on the market place entry.

**Comment by lkoe** [comment]
Eclipse Marketplace entry has been updated to the new update site URL (https://checkstyle.github.io/eclipse-cs/update). Marketplace installation tested successfully.
