### ISSUE TITLE
Update Site no more available

### ISSUE THREAD

**Issue by JonasHelming** [checkstyle/eclipse-cs#45]
It seems you have deprecated http://eclipse-cs.sf.net/update
It is not reachable anymore. As I do not see an update site on the website anymore, I assume this happened on purpose. As the plugin is available on the market place, there must be an update site. It would be great, if you could share the URL and ideally keep it stable. Please note that a lot of people are consuming update sites, e.g. via an Oomph profile. Those installations will fail, if the update site gets deprecated.
by the way: Thanks for providing this great plugin!

**Comment by lkoe** [comment]
Indeed the update site has changed as part of the migration to Github. The new update site URL is: https://checkstyle.github.io/eclipse-cs/update

The old URLs http://eclipse-cs.sourceforge.net/update/ and http://eclipse-cs.sf.net/update should still be working, redirecting to the new location.
However, there seems to have been maintenance work @Sourceforge infrastructure during the weekend and even today, and the URLs have not been available at all times. It seems to work again now.

**Comment by JonasHelming** [comment]
OK, we will consume https://checkstyle.github.io/eclipse-cs/update then. We had frequent issues with the SourceForge URLs since a very long time. More precisely, we had very slow transfers.
I hope https://checkstyle.github.io/eclipse-cs/update will be a stable URL?
If so, it would be great to communicate it on the download page for other users, too.
Thank you for your answer!

**Comment by lkoe** [comment]
Yes, the new URL is meant to be stable. Unless Github starts f****** things up as SF did. But I am hoping for the best. ;-)
The "how to install" page (https://checkstyle.github.io/eclipse-cs/#!/install) already lists the new URL.
But I guess we can announce the change more prominently on the home page.
