### ISSUE TITLE
How to create installable Eclipse-CS snapshot plugin artifacts?

### ISSUE THREAD

**Issue by rnveach** [checkstyle/eclipse-cs#475]
### Discussed in https://github.com/checkstyle/eclipse-cs/discussions/473

<div type='discussions-op-text'>

<sup>Originally posted by **rnveach** February  5, 2023</sup>
I run `mvn clean package` on master and get a successful build. I try to go to Eclipse and install the plugin from `eclipse-cs\net.sf.eclipsecs-updatesite\target\repository` but it gets the following error:

````
Cannot complete the install because one or more required items could not be found.
  Software being installed: Eclipse Checkstyle Plug-in 10.4.0.202302051801 (net.sf.eclipsecs.feature.group 10.4.0.202302051801)
  Missing requirement: Eclipse Checkstyle 10.4.0.202302051801 (net.sf.eclipsecs.core 10.4.0.202302051801) requires 'java.package; org.dom4j 2.1.3' but it could not be found
````

When comparing my packaged version versus the release, I notice that the core JAR is missing the 3rd party JARs (dom4j, snakeyml, javaassist). I assume this is why Eclipse fails to install, but I am not seeing what is missing to include them.

I also noticed my doc JAR is 1000x larger than the release version, but I assume this is unrelated.

This is the same with `net.sf.eclipsecs-updatesite/target/net.sf.eclipsecs-updatesite_10.4.0.202302051801.zip`.

I have no issues compiling the project in Eclipse (no errors).</div>

===========

It appears 32d604929ad7f24488cd175e2f587b49986d5056 broke creating usable Eclipse-CS plugin artifacts with Eclipse-CS' own package instructions.

https://github.com/checkstyle/eclipse-cs/blob/563ce31909a22dfd581d58498c5d79f26bd6a84b/README.md?plain=1#L36-L38

Creating an artifact from 7e02d4eb28eaf8b379d4215556f5604fb382970d (the commit directly before 32d604929ad7f24488cd175e2f587b49986d5056) produces an plugin artifact with the necessary JARs in the lib folder. I tested and was able to install the artifact produced without issue.

Starting with 32d604929ad7f24488cd175e2f587b49986d5056, the necessary JARs are missing and I can no longer install what was produced.

I am unsure if this an instructional issue or if it is a bigger issue.

**Comment by rnveach** [comment]
@Bananeweizen Are you able to help clarify the issue when switching to wrapped OSGi bundles?

@Calixte Since you do releases, can you clarify if this impacts you too if you have time?

**Comment by Bananeweizen** [comment]
@rnveach  What's the difference between the comment in text and in title? I thought both lead to auto-closing on merge?
