### ISSUE TITLE
Master build at Travis is failing on git diff

### ISSUE THREAD

**Issue by romani** [checkstyle/eclipse-cs#479]
https://app.travis-ci.com/github/checkstyle/eclipse-cs/jobs/596294909

```
The command "./.ci/travis.sh run-command "$CMD"" exited with 0.
0.13s$ ./.ci/validation.sh git-diff
Changes to only docs/sitemap.xml:
diff --git a/docs/sitemap.xml b/docs/sitemap.xml
index 1fc0b33..fc25135 100644
--- a/docs/sitemap.xml
+++ b/docs/sitemap.xml
@@ -12,77 +12,77 @@
   -->
   <url>
     <loc>https://checkstyle.org/eclipse-cs/</loc>
-    <lastmod>2022-11-15T19:19:41Z</lastmod>
+    <lastmod>2023-02-19T01:01:04Z</lastmod>
     <changefreq>weekly</changefreq>
   </url>
```

I think we need to disable git diff validaiton in eclipse-cs or make it smart to exclude some files.

**Comment by romani** [comment]
@rnveach

**Comment by rnveach** [comment]
Fix should be in https://github.com/checkstyle/eclipse-cs/pull/474 . Waiting for merge.

**Comment by rnveach** [comment]
> Changes to only docs/sitemap.xml:

This is not failure in git diff. This file is expected to change on every run and is just for display purposes.

Failures only come after this file.

**Comment by Bananeweizen** [comment]
This works now: https://app.travis-ci.com/github/checkstyle/eclipse-cs/jobs/599818587#L975
The timestamps are now based on the latest git commit of the docs module: https://github.com/checkstyle/eclipse-cs/commit/43a761e9869b9db53ba05fe49a692713560d51b5
