### ISSUE TITLE
Shorten progress messages

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#539]
Right now the progress messages have some superfluous text. They are created as `Checking [config name]: Checking file [file name]`. Example:
![grafik](https://github.com/checkstyle/eclipse-cs/assets/406876/04e8efd3-05e6-426a-87aa-5779b151492d)

We should remove the `Checking file` part, as it doesn't add any value, but increases the size, thereby leading to shortening of the label in case of a small view layout.

Similarly we should remove the `Running ` prefix from the job title. Without it, no information is lost, and the most important information (the checkstyle tool name) is the first word of the label, which helps speed reading.

**Comment by farhan-afridi** [comment]
Sir I would like to work on this, if you could assign me this issue.

**Comment by Calixte** [comment]
@farhan-afridi Please feel free to submit a pull request for this.

**Comment by Bananeweizen** [comment]
PR available in https://github.com/checkstyle/eclipse-cs/pull/553
