### ISSUE TITLE
Use checkstyle sources zip  and  '-all.jar' from github

### ISSUE THREAD

**Issue by romani** [checkstyle/eclipse-cs#54]
https://github.com/checkstyle/eclipse-cs/wiki/How-to-update-to-a-new-Checkstyle-core-version

>Download matching Checkstyle sources zip: checkstyle-X.X-src.zip

Checkstyle is about to migrate from sourceforge to github.io.
So we try to minimize dependency to sourceforge.
Is it possible to grab sources from github ?
https://github.com/checkstyle/checkstyle/releases
https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-8.8

FYI:
>Download latest checkstyle-X.X-all.jar from Checkstyle download page.

I uploaded 8.8 version to https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-8.8
(just a copy from sourceforge).

**Comment by vorburger** [comment]
> Is it possible to grab sources from github ?

I think so, from [the releases link you've also given](https://github.com/checkstyle/checkstyle/releases), as far as I understand how GitHub works, any Git tag is automatically offered as sources ZIP (without having to "deploy" anything), e.g. [this ZIP](https://github.com/checkstyle/eclipse-cs/archive/8.8.0.zip) and [as tar.gz](https://github.com/checkstyle/eclipse-cs/archive/8.8.0.tar.gz).

> Download latest checkstyle-X.X-all.jar from Checkstyle download page. I uploaded 8.8 version to 

right for the binary built JAR (not sources) you'll have to upload. But aren't those always also going to be on Maven central anyway (and automatically deployed there) to which you could put a direct DL link - do you think it's important to also have the non-sources JAR on the GitHub releases page?

**Comment by Bananeweizen** [comment]
Since the process described on that wiki page is a manual one, I see no problem at all, independent of whether we grab artifacts from Maven or from Github directly. I'll give it a try this evening.

**Comment by romani** [comment]
> do you think it's important to also have the non-sources JAR on the GitHub releases page?

I always surprised how checkstyle is used in this world, smb download such files according to sourceforge statistic of download, so I just put same stuff to another location.

**Comment by Bananeweizen** [comment]
I've used the all.jar and the sources.zip from the github 8.9 release now, and that worked well. The wiki has been adapted, too.
