### ISSUE TITLE
community standards

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#571]
someone with admin access please set the
* code of conduct
* security policy
to the same values as in the main checkstyle project.

See https://github.com/checkstyle/eclipse-cs/community if the above is unclear.

Please do not set the other missing values, as the templates for pull requests etc. don't really fit to this project. Or can we eventually take a copy of the missing ones into this repository, and then modify them to our needs?

**Comment by rnveach** [comment]
I don't believe these require admins. These are files in the repo.

> code of conduct

https://github.com/checkstyle/checkstyle/blob/master/.github/CODE_OF_CONDUCT.md

> security policy

https://github.com/checkstyle/checkstyle/blob/master/SECURITY.md
