### ISSUE TITLE
usage of checkstyle.org domain

### ISSUE THREAD

**Issue by romani** [checkstyle/eclipse-cs#58]
build failure on checkstyle project
https://app.codeship.com/projects/124310/builds/32931364?pipeline=c32640b0-6e3b-4a5b-bed8-5f40292ea9f7

We have link validation plugin, here is failure:
```
------------ grep of linkcheck.html--BEGIN
<td><i><a class="externalLink" href="https://checkstyle.github.io/eclipse-cs/">https://checkstyle.github.io/eclipse-cs/</a>: 301 Moved Permanently</i></td></tr></table></td></tr>
------------ grep of linkcheck.html--END
```
It is not blocking failure, but still ...

http://wheregoes.com/retracer.php
```
https://checkstyle.github.io/eclipse-cs/
301 Redirect
http://checkstyle.org/eclipse-cs/
```

checkstyle.org is only 1 day alive, as core project did not migrate to it yet, will not migrate for several months.
there is no guaranty on completion of site move.

Are you sure that it is better to do such redirection now ?
Or nothing is changed on eclipse-cs side ...  is this automatic behavior changes by github ?

**Comment by romani** [comment]
If you did nothing, my activity at https://github.com/checkstyle/checkstyle/issues/5601 might cause this redirect.

**Comment by Bananeweizen** [comment]
I cannot comment here, the website-related administration is by @lkoe.

**Comment by Bananeweizen** [comment]
When this has been sorted out, the repository description of eclipse-cs at the top of https://github.com/checkstyle/eclipse-cs can be updated to use the new URL directly.

**Comment by lkoe** [comment]
Hmm, it seems that happened automatically because the eclipse-cs was already on gh-pages. Now that the main organisation is connected to the checkstyle.org domain I figure Github automatically redirects to the new domain for all subprojects which are on gh-pages.
So I am not quite sure what I should do about that, since ultimately it's the desired result, no?

**Comment by romani** [comment]
Ultimately - yes.
I just do not want to make problems to you, while we try to migrate to new hosting.
I am closing issue for now, if you find any problem please let me know.
