### ISSUE TITLE
Request read-write access

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#6]
As discussed over at the sourceforge post I would like to request write access to this repository.

**Comment by romani** [comment]
@lkoe , you can do this yourself (you should have admin rights in this project) , if you unfamilar with github UI , I can do this but I need your approval.

**Comment by lkoe** [comment]
Thanks for the recent work and welcome to the team, Michael!

**Comment by romani** [comment]
I am not in position to tell you how make your work, but here is some practices from core project:
1) Having RW access, does not give you right to put in project non-approved changes or changes that did not pass review. All should pass PRs/CIs.
2) RW access gives you access to CI settings, issues management.
3) All PRs should pass two reviews, if PR from maintainer - only one review is enough.
4) Review is not a bureaucracy. It is to let others be aware of what is going on and why changes are required. Sharing a knowledge. Recheck that CI is ok. Avoiding bunch of additional changes that was forgotten. Only very minor(non-functional) fixes are ok to merge without review.
5) let @lkoe only, to make a label "approved" for some time.

**Comment by Bananeweizen** [comment]
Thanks a lot, Lars. I'll try to follow the advice given by Roman, as I know the same principles from many other projects.

**Comment by Bananeweizen** [comment]
Uhm, either I misunderstood you or something is not yet right. I don't have write access to the repository, as github just stated.
