### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by OscarCarrilloTR** [checkstyle/eclipse-cs#648]
I was trying to install the plugin within the steps written down in the README.md file but I've received the following error:

![image](https://github.com/checkstyle/eclipse-cs/assets/91084534/54c238f0-0a6b-42ce-83cc-3737f8498233)

Am I doing something wrong?

Eclipse IDE for Enterprise Java and Web Developers
Version: 2021-06 (4.20.0)
Build id: 20210612-2011

**Comment by Bananeweizen** [comment]
While I've seen quite some errors over the years, I've never seen that public key error message yet. I have no idea. That being said, you are on the _oldest_ version we support at all, therefore it might be a good idea to upgrade to a recent Eclipse version and try again.

**Comment by OscarCarrilloTR** [comment]
Thanks @Bananeweizen I'll give it a try later with a newer version of Eclipse, greetings.
