### ISSUE TITLE
Update urls to be http for checkstyle.org

### ISSUE THREAD

**Issue by romani** [checkstyle/eclipse-cs#66]
Based on discussion at https://github.com/checkstyle/checkstyle/issues/5661#issuecomment-378829771

Commit https://github.com/checkstyle/eclipse-cs/commit/7bec79dbdcd9ca24a5155474bbf20504a2054ab0 reverted or urls need to changed back to http.

Https can not be provided for now, so let's be honest with users.

Probably, usage of GitHub.io urls(https://checkstyle.github.io/) should be avoided as it redirects to checkstyle.org to whole organization.

**Comment by Bananeweizen** [comment]
I've created a pull request for source files. However, the sourceforge redirection and the marketplace entry need to be updated by @lkoe.

**Comment by lkoe** [comment]
To be honest I am less than thrilled. I don't understand the urgency to move on with the migration to checkstyle.org when it is a clear step back from the services provided by https://checkstyle.github.io/ until a solution for TLS is provided.

**Comment by romani** [comment]
unfortunately it was side effect of sourceforge maintenance/transition that was about 2 month long. I have a feelling that sourceforge is dieing slowly. I will remove all resources from sourceforge eventually (too much problems). Own domain was decision that I postponed for while, but we have dtd files that all configs rely on, we recently completed will copy from com.puppycrawl to sourceforge , one more migration from sourceforge to github.io extra problem for users. So I agreed on community preasure to have own domain.

I do not have time to make migration quick, so there will be some time when we exists on both locations. TLS is under discussion on how to resolve, if you know how to make it please let us know. Ones we make it reliable we will switch to https. 

But both of us existed without https for many years, so continue to use http I think is ok for some time.
Fact that now our web sites are merged to same domain become a surprice for me. 

Can you share with me details on how you are redirecting your web site to github.io ? I might miss smth but I donot see your website resources on github under organization.

**Comment by lkoe** [comment]
I posted this link to the original discussion, don't know how feasible, though: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by lkoe** [comment]
All URLs (except those I've missed) have been changed the checkstyle.org
