### ISSUE TITLE
Remove Reflections Library Usage

### ISSUE THREAD

**Issue by rnveach** [checkstyle/eclipse-cs#682]
Pulled from https://github.com/checkstyle/eclipse-cs/pull/659#issuecomment-1987274759 and https://github.com/checkstyle/eclipse-cs/pull/681#issuecomment-2028775465 ,

We need to remove reflections library because since the move from Java 8, it hasn't been updated and basically does nothing. https://github.com/ronmamo/reflections/issues/465 https://github.com/ronmamo/reflections/issues/186

It is just doing a bare bones, common java code load. We should do that instead unless something better is found.

**Comment by rnveach** [comment]
For resources, Reflections basically calls `ClassLoader.getResources`.
https://github.com/ronmamo/reflections/blob/master/src/main/java/org/reflections/util/ClasspathHelper.java#L103

**Comment by Bananeweizen** [comment]
@rnveach if you are going to also work on this for the main project, please be aware that the usage of the classgraph library seems to avoid quite some corner cases that you would have with rolling an own implementation in Java:
* it knows about java module paths, too, which seem to be handled differently than class paths
* it scans without actually loading the classes, therefore it should be more performant
