### ISSUE TITLE
Exclude from checking files in sync with the source repository not working

### ISSUE THREAD

**Issue by mhagnumdw** [checkstyle/eclipse-cs#714]
I've tested this option a few times and it doesn't work.

I'm using git.

Documentation: https://checkstyle.org/eclipse-cs/#!/filters:~:text=Files%20in%20sync%20with%20the%20source%20repository

To reproduce:
- I change something in the code to disagree with a checkstyle rule and Eclipse warns me - ok here
- In the checkstyle settings in Eclipse, I activated the option `sync with the source repository not working` in the `Exclude from checking...` section
- Eclipse starts building, finishes, and no longer displays the problem with the rule - **here we have a problem!**
- if I uncheck the `sync with the source repository not working` option, Eclipse returns to displaying the problem with the rule - ok again

**Comment by mhagnumdw** [comment]
Thank you very much!

When will the release be?

**Comment by Calixte** [comment]
> When will the release be?

It has been released.

**Comment by mhagnumdw** [comment]
Great! It works now. Thanks.
