### ISSUE TITLE
How can I easily fix Checkstyle errors

### ISSUE THREAD

**Issue by ifindya** [checkstyle/eclipse-cs#743]
Tried two ways:
Right click on the java file in Package Explorer or whatever, and select 'Apply Checkstyle fixes'.
Click on the error in the problems view, and select 'Quick fix'. 

But none of them worked. I am using: Eclipse Version: 2024-06 (4.32.0)
Eclipse Checkstyle 10.18.0

**Comment by romani** [comment]
@Bananeweizen, do we have any list of what Check we support for quick fix?

**Comment by rnveach** [comment]
@romani https://github.com/checkstyle/eclipse-cs/tree/7b87f37fc1efe032a58c184345f5ddacdd277988/net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes

**Comment by Bananeweizen** [comment]
https://github.com/checkstyle/eclipse-cs/blob/7b87f37fc1efe032a58c184345f5ddacdd277988/net.sf.eclipsecs.ui/plugin.xml#L547-L618 might be easier to read.
