### ISSUE TITLE
Move issues from SourceForge tracker to Github

### ISSUE THREAD

**Issue by lkoe** [checkstyle/eclipse-cs#8]
Part of the activities to migrate the project from SF is to move issues (bugs, feature requests).
If possible conversations in the old tickets should be replicated.

**Comment by Bananeweizen** [comment]
The most recent automated tool I found is https://github.com/cmungall/gosf2github. However, I never used that myself, so I'm not sure how well the original conversion and authors are still readable. Generally, all of the new tickets will have yourself as the author.

**Comment by Bananeweizen** [comment]
I referenced the wrong issue in my commit, therefore re-opening.

**Comment by lkoe** [comment]
I've come to the conclusion that I don't want to do this by myself.
Although people took the time to originally report the problem, which is appreciated, I value my own time as well.
Thus I will be closing all tickets over at SF with an appropriate comment to open a new bug/rfe here, if so desired.
Disagreement or offers to volunteer are still welcome, until the deed is done.

**Comment by Bananeweizen** [comment]
Seems reasonable, even if it puts additional effort on the original reporters. The benefit of this approach is a very healthy cleaning of no more reproducable or nor more important issues...

**Comment by rtack** [comment]
could be closed as a decision has been made to not put more effort into it.
