### ISSUE TITLE
Marketplace install fails with HTTP 301

### ISSUE THREAD

**Issue by sorin-costea** [checkstyle/eclipse-cs#81]
I'm not behind any proxy and the error log entry is below:

eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_152
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.equinox.p2.transport.ecf
Error
Tue May 22 10:58:02 CEST 2018
HTTP Server Unknown HTTP Response Code (301):https://checkstyle.github.io/eclipse-cs/update/compositeContent.xml

org.eclipse.ecf.filetransfer.BrowseFileTransferException: General connection error with response code=301 and header(0)=HTTP/1.1 301 Moved Permanently
	at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:134)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

```

**Comment by lkoe** [comment]
Whatever was wrong at the time should now work.
