### ISSUE TITLE
Missing option useContainerOrderingForStatic for "Import Order Check" module

### ISSUE THREAD

**Issue by sebthom** [checkstyle/eclipse-cs#83]
When configuring checkstyle via Eclipse-CS it is not possible to set the useContainerOrderingForStatic option introduced with https://github.com/checkstyle/checkstyle/issues/3101
Enabling this option however is required to make ImportOrderCheck work correctly with the way Eclipse orders imports.

While one can manually add the field to the XML config file, when modifying the checkstyle config with Eclipse CS, the useContainerOrderingForStatic property is removed on save. So it might also be a good idea if Eclipse-CS would not silently remove properties it does not know.

**Comment by rnveach** [comment]
This should be fixed by https://github.com/checkstyle/eclipse-cs/pull/79 if it is ever merged and released.
https://github.com/checkstyle/eclipse-cs/pull/79/files#diff-53eed6bd866d767089e9dbc4e8c404abR76

**Comment by lkoe** [comment]
Fixed in master, pending the 8.11.0 release.

**Comment by lkoe** [comment]
Fix now release with 8.10.1 version.
