### ISSUE TITLE
Plugin changing schema URLs to www.puppycrawl.com

### ISSUE THREAD

**Issue by romani** [checkstyle/eclipse-cs#85]
After operating with config in eclipse-cs 8.10.0 UI, there is a change:
```
--- a/checkstyle-8.10-sevntu-1.29.xml
+++ b/checkstyle-8.10-sevntu-1.29.xml
@@ -1,11 +1,11 @@
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" 
-   "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" 
+   "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
```

after https://github.com/checkstyle/checkstyle/issues/5722  (released in 8.11) all DTD public names are changed , please update them in plugin they are stored separare copy.

Additionally all DTDs were moved to checkstyle.org  in [commit](https://github.com/checkstyle/checkstyle/commit/3f773b1bd6dee93fb1c18d219a9846b471b2d0b2#diff-0e1387564790949063caff904154c1a2).

http://www.puppycrawl.com do not have DTD that were recently fixed, and will never have. we do not have control over it such domain.

so DOCTYPE should not be changed, or upgraded to most recent location 
```
"-//Checkstyle//DTD Check Configuration 1.3//EN"
    "https://checkstyle.org/dtds/configuration_1_3.dtd">
```

**Comment by rnveach** [comment]
@Ikoe You include the all jar in eclipse-cs ( https://github.com/lkoe/eclipse-cs/blob/master/net.sf.eclipsecs.checkstyle/ ) , which comes with the DTDs . Why don't you just pull the DTDs from that instead of duplicating them and maintaining a 2nd copy?

**Comment by lkoe** [comment]
@rnveach 
> Why don't you just pull the DTDs from that instead of duplicating them and maintaining a 2nd copy?
I do! :-) There is no copy of the DTD in eclipse-cs, just references to the public/system name for writing Checkstyle configuration files from the plugins configuration editor. Those had been out of date.

**Comment by rnveach** [comment]
Sorry, your right.
