### ISSUE TITLE
Create wiki pages documenting update/release process

### ISSUE THREAD

**Issue by lkoe** [checkstyle/eclipse-cs#9]
Create wiki pages detailing the process of updating the plugin to a new Checkstyle core version and creating a new plugin release.

**Comment by lkoe** [comment]
I've create
https://github.com/checkstyle/eclipse-cs/wiki/How-to-release
and
https://github.com/checkstyle/eclipse-cs/wiki/How-to-update-to-a-new-Checkstyle-core-version

Please review

**Comment by romani** [comment]
> checkstyle-X.X-src.zip

good to know that you need this :)

>Open Checkstyle release notes

as a hint , we try our best to classify issues after a fix.
Notes and Bugs - should affect metadata
New - affects metadata
Braking compatibilities - affects metadata

Not sure it that helps, but here how I track what is affecting soname metadata - https://github.com/checkstyle/sonar-checkstyle/issues/136

@lkoe , please do release base on 8.7, as 8.6 have good filters to use, but 8.7 it blocks usage of extensions are we did removal of guava from API, so re-compilation is required. I was forced to disable sevntu in all CIs.

@Bananeweizen , please review, I try to sat away from new projects as I have huge backlog in core project, it would be awesome if you cam make just a technical release right after 8.7 to make sure you can do it.

to attract more contributors, it is better to think about some plan for releases (base on time period, commits, any other trigger).

**Comment by lkoe** [comment]
> @lkoe , please do release base on 8.7, as 8.6 have good filters to use, but 8.7 it blocks usage of extensions are we did removal of guava from API, so re-compilation is required. I was forced to disable sevntu in all CIs.

Release 8.7.0 is out :-)

> to attract more contributors, it is better to think about some plan for releases (base on time period, commits, any other trigger).

I think the main driver should be the Checkstyle core releases, for the time being. Should there be a significant uptake in new features this could be revisited, however.

**Comment by Bananeweizen** [comment]
Those wiki pages are quite well described. I just don't get one thing: The updating of the metadata. I've checked your changes for 8.7.0 there and I have no clue where you got the information on what to update. E.g. where did you see that the @exception parameter was added to NonEmptyAtClause by the Checkstyle team?

**Comment by lkoe** [comment]
> E.g. where did you see that the exception parameter was added to NonEmptyAtClause by the Checkstyle team?

Often the item in the release notes strongly hints whether metadata is affected (new check, new option...). When it's less clear I check the related PR/commits - for instance https://github.com/checkstyle/checkstyle/commit/d5c3d379ad0d6e0a1511162075981806d2ab2d8f
It can be quite tedious (and error prone) at times to hunt such suble things, maybe someday Checkstyle core will itself expose the metadata directly. I still want to raise a ticket about that...

**Comment by romani** [comment]
release notes titles and groups should be enough to check what should be updated. We try our best to make it clear, but there are still rooms to improve.

> maybe someday Checkstyle core will itself expose the metadata directly. I still want to raise a ticket about that... 

there is #3 . We already have 2 forms of metadata: eclipse-cs and sonar. The same pain in both projects. Smth should be done in checkstyle to ease, but most likely main generation modules should be in certain projects as there are third-party extensions for eclipse-cs and sonar.

> I think the main driver should be the Checkstyle core releases, for the time being. 

I added point to checkstyle release to make issue on eclipse-cs - https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release
@Bananeweizen , we release checkstyle at last weekends of month (milestones are always accurate in core project), we will help to go over changes to make meta-data update smooth.
