### ISSUE TITLE
Checkstyle execution failed due to an internal error. Please check the error log for details.

### ISSUE THREAD

**Issue by srasku** [checkstyle/eclipse-cs#94]
I am running Eclipse Photon (4.8.0) with [Checkstyle 8.11.0 plugin](https://bintray.com/eclipse-cs/eclipse-cs/update-site-archive/8.11.0).

When I right-click my file and select "Checkstyle >> Check Code with Checkstyle" I get "Checkstyle execution failed due to an internal error.  Please check the error log for details."

**Comment by srasku** [comment]
Here's the log file and the checkstyle configuration.

[metadata.log](https://github.com/checkstyle/eclipse-cs/files/2254392/metadata.log)

[checkstyle.txt](https://github.com/checkstyle/eclipse-cs/files/2254397/checkstyle.txt)

**Comment by rnveach** [comment]
From the CLI checkstyle, your configuration is fine for version 8.11 .

The metadata log file doesn't really say any errors for eclipse-cs. It is just showing errors for jgit and gradle.

> java.lang.ClassNotFoundException: org.eclipse.jgit.lfs.BuiltinLFS cannot be found by org.eclipse.egit.core_5.0.0.201806131550-r
> org.gradle.api.UncheckedIOException: Cannot download published Gradle versions.
> java.net.UnknownHostException: dev.eclipse.org: nodename nor servname provided, or not known

**Comment by srasku** [comment]
I've exported the Eclipse error log and attached it.  I didn't notice anything regarding `eclipse-cs`.

* [Eclipse Error.log](https://github.com/checkstyle/eclipse-cs/files/2266702/Eclipse.Error.log)

**Comment by romani** [comment]
Looks like it is unrelated to checkstyle plug-in.
@srasku , is it happening all the time ? Please share so other details of your eclipse (os type and version, Java version, other plug-in version). Looks like problem with git plugin in eclipse.

**Comment by srasku** [comment]
I'm running on macOS 10.13.5.
```
$ javac -version
javac 1.8.0_144
```

I've removed the Git plugins but the problem still occurs.

![eclipse plugin versions](https://user-images.githubusercontent.com/2049005/43798589-e620b80e-9a3f-11e8-82a9-ffc5f60fa874.png)

**Comment by srasku** [comment]
I've updated egit and I don't see that error any more.  

* [Updated egit.log](https://github.com/checkstyle/eclipse-cs/files/2272253/Updated.egit.log)

I also reconfigured my proxy which allowed me to connect to Eclipse Marketplace.  I wasn't able to do that before.  Unfortunately, Checkstyle is still not working.

**Comment by romani** [comment]
From your log :
>!MESSAGE Checkstyle-Plugin: SuppressionCommentFilter is not allowed as a child in Checker
!STACK 0
com.puppycrawl.tools.checkstyle.api.CheckstyleException: SuppressionCommentFilter is not allowed as a child in Checker

Looks like your confirmation need to be updated as you updated version of checkstyle.
Take a look at breacking changes in http://checkstyle.sourceforge.net/releasenotes.html#Release_8.1 for SuppressionCommentFilter and follow migration recommendations.

**Comment by srasku** [comment]
Thanks, @rnveach.  I didn't checkin my Checkstyle configuration.  Restoring it is the final step to solving this problem.  

It's working now.

**Comment by msaifusmani** [comment]
<img width="1347" alt="Screen Shot 2020-03-24 at 11 42 31 PM" src="https://user-images.githubusercontent.com/43828922/77500706-3ed53d00-6e2c-11ea-8ff8-b6ace4ebd9bb.png">
I am also getting the same error with regards to Checkstyle, @srasku how did you fix it? How did you restore it as you said in your last response?
