### ISSUE TITLE
Add missing keybinding for "Check Code with CheckStyle" command

### ISSUE THREAD

**Issue by olivarre** [checkstyle/eclipse-cs#99]
Currently, there is no way to tie this command to a shortcut key because the key binding for it isn't defined in plugin.xml. 

I've added the modifications to plugin.xml to bind the "Check Code With CheckStyle" command to a key that is configurable under Eclipse > Preferences > Keys and default it to M1+M2+K (ex: CTRL+ALT+K). This way, users can quickly CheckStyle on the active editor (or files selected in the Package Explorer) without having to use the context menus or rely on building. 

I'll commit the changes if this issue is approved.

**Comment by infiniator** [comment]
Hi, is it possible to set this up for myself? I am kinda clueless about how to go about doing this, it'll be helpful if you can help with some starter docs to get this done.
